namespace HearthDb
{
    /* THIS CLASS WAS GENERATED BY HearthDb.CardIdGenerator. DO NOT EDIT. */
    public partial class CardIds
    {
        public partial class NonCollectible
        {
            public class Whizbang
            {
                public const string WhizbangTheWonderfulHeroic = "BOT_914h";
                public const string ZayleShadowCloakHeroic = "DAL_800h";
                public const string WonderousWhizbangHeroic = "TOY_700h";
            }
        }
    }
}