namespace HearthDb
{
    /* THIS CLASS WAS GENERATED BY HearthDb.CardIdGenerator. DO NOT EDIT. */
    public partial class CardIds
    {
        public partial class Collectible
        {
            public class Invalid
            {
                public const string SpawningPool = "SC_000";
                public const string BroodQueen = "SC_003";
                public const string KerriganQueenOfBlades = "SC_004";
                public const string Zergling = "SC_010";
                public const string NydusWorm = "SC_015";
                public const string JimRaynor = "SC_400";
                public const string Scv = "SC_401";
                public const string Starport = "SC_403";
                public const string Ghost = "SC_408";
                public const string LiftOff = "SC_410";
                public const string ChronoBoost = "SC_750";
                public const string WarpGate = "SC_751";
                public const string PhotonCannon = "SC_753";
                public const string Artanis = "SC_754";
                public const string VoidRay = "SC_783";
            }
        }
    }
}