namespace HearthDb
{
    /* THIS CLASS WAS GENERATED BY HearthDb.CardIdGenerator. DO NOT EDIT. */
    public partial class CardIds
    {
        public partial class NonCollectible
        {
            public class Whizbang
            {
                /// <summary>
                /// (No Text)<br/>
                /// 0-Cost Hero
                /// </summary>
                public const string WhizbangTheWonderfulHeroic = "BOT_914h";

                /// <summary>
                /// (No Text)<br/>
                /// 0-Cost Hero
                /// </summary>
                public const string ZayleShadowCloakHeroic = "DAL_800h";

                /// <summary>
                /// (No Text)<br/>
                /// 0-Cost Hero
                /// </summary>
                public const string WonderousWhizbangHeroic = "TOY_700h";
            }
        }
    }
}