namespace HearthDb
{
    /* THIS CLASS WAS GENERATED BY HearthDb.CardIdGenerator. DO NOT EDIT. */
    public partial class CardIds
    {
        public partial class Collectible
        {
            public class Invalid
            {
                /// <summary>
                /// Get a 1/1 Zergling. <b>Deathrattle:</b> Your Zerg minions have <b>Rush</b> this turn.<br/>
                /// 1-Cost Location
                /// </summary>
                public const string SpawningPool = "SC_000";

                /// <summary>
                /// At the end of your turn, get a Larva that transforms into random Zerg minions.<br/>
                /// 3-Cost 2/5 Minion
                /// </summary>
                public const string HiveQueen = "SC_003";

                /// <summary>
                /// <b>Battlecry:</b> Summon two 2/5 Hive Queens. Deal 3 damage to all enemies.<br/>
                /// 7-Cost Hero
                /// </summary>
                public const string KerriganQueenOfBlades = "SC_004";

                /// <summary>
                /// <b>Battlecry:</b> Summon a copy of this.<br/>
                /// 1-Cost 1/1 Minion
                /// </summary>
                public const string Zergling = "SC_010";

                /// <summary>
                /// Draw two Zerg cards. They cost (1) less.<br/>
                /// 3-Cost Spell
                /// </summary>
                public const string NydusWorm = "SC_015";

                /// <summary>
                /// <b>Battlecry:</b> Relaunch every <b>Starship</b> that you launched this game.<br/>
                /// 7-Cost Hero
                /// </summary>
                public const string JimRaynor = "SC_400";

                /// <summary>
                /// <b>Battlecry:</b> Your next <b>Starship</b> launch costs (2) less.<br/>
                /// 1-Cost 1/3 Mechanical Minion
                /// </summary>
                public const string Scv = "SC_401";

                /// <summary>
                /// Summon a 2/1 <b>Starship Piece</b> with an effect when launched.<br/>
                /// 2-Cost Location
                /// </summary>
                public const string Starport = "SC_403";

                /// <summary>
                /// <b>Stealth</b>. <b>Battlecry:</b> If you're building a <b>Starship</b>, destroy the lowest-Cost card in your opponent's hand.<br/>
                /// 4-Cost 6/2 Minion
                /// </summary>
                public const string Ghost = "SC_408";

                /// <summary>
                /// Draw 2 Terran cards. Summon a 2/1 <b>Starship Piece</b> with an effect when launched.<br/>
                /// 3-Cost Spell
                /// </summary>
                public const string LiftOff = "SC_410";

                /// <summary>
                /// Draw 2 Protoss cards. Summon a 3/4 Zealot with <b>Charge</b>.<br/>
                /// 4-Cost Spell
                /// </summary>
                public const string ChronoBoost = "SC_750";

                /// <summary>
                /// Your next Protoss minion costs (3) less.<br/>
                /// 4-Cost Location
                /// </summary>
                public const string WarpGate = "SC_751";

                /// <summary>
                /// Deal $3 damage. If this kills a minion, your Protoss minions cost (1) less this game.<br/>
                /// 2-Cost Spell
                /// </summary>
                public const string PhotonCannon = "SC_753";

                /// <summary>
                /// <b>Battlecry:</b> Summon two 3/4 Zealots with <b>Charge</b>. Your Protoss minions cost (2) less this game.<br/>
                /// 7-Cost Hero
                /// </summary>
                public const string Artanis = "SC_754";

                /// <summary>
                /// <b>Rush</b>, <b>Divine Shield</b> <b>Battlecry:</b> If this costs (0), gain +2/+2.<br/>
                /// 3-Cost 3/2 Mechanical Minion
                /// </summary>
                public const string VoidRay = "SC_783";
            }
        }
    }
}