namespace HearthDb
{
    /* THIS CLASS WAS GENERATED BY HearthDb.CardIdGenerator. DO NOT EDIT. */
    public partial class CardIds
    {
        public partial class Collectible
        {
            public class Deathknight
            {
                /// <summary>
                /// Give a friendly Undead <b>Poisonous</b>.<br/>
                /// 2-Cost Spell
                /// </summary>
                public const string PoisonBreathCore = "CORE_EDR_002";

                /// <summary>
                /// You gain twice as many <b>Corpses</b> as normal. <b>Battlecry:</b> Draw a card that spends <b>Corpses</b>.<br/>
                /// 3-Cost 2/4 Undead Minion
                /// </summary>
                public const string FalricCore = "CORE_EDR_003";

                /// <summary>
                /// <b>Taunt</b> Costs Health instead of Mana if your hero was healed this turn.<br/>
                /// 3-Cost 3/4 Undead Minion
                /// </summary>
                public const string DeathMetalKnightCore = "CORE_ETC_523";

                /// <summary>
                /// <b>Discover</b> a <b>Temporary</b> Dark Transformation, Howling Blast, or Death Strike.<br/>
                /// 1-Cost Spell
                /// </summary>
                public const string ArthassGiftCorePlaceholder = "CORE_GIFT_04";

                /// <summary>
                /// After your hero attacks and kills a minion, gain 2 <b>Corpses</b>.<br/>
                /// 3-Cost Weapon
                /// </summary>
                public const string SoulbreakerCore = "CORE_RLK_012";

                /// <summary>
                /// Detonate a <b>Corpse</b> to deal $1 damage to all minions. If any are still alive, repeat this.<br/>
                /// 5-Cost Spell
                /// </summary>
                public const string CorpseExplosionCore = "CORE_RLK_035";

                /// <summary>
                /// Refresh 2 Mana Crystals.<br/>
                /// 0-Cost Spell
                /// </summary>
                public const string HornOfWinterCore = "CORE_RLK_042";

                /// <summary>
                /// Give your hero +5 Health. Spend 3 <b>Corpses</b> to gain 5 more and draw a card.<br/>
                /// 2-Cost Spell
                /// </summary>
                public const string VampiricBloodCore = "CORE_RLK_051";

                /// <summary>
                /// <b>Taunt</b> <b>Battlecry:</b> Summon two copies of this minion.<br/>
                /// 4-Cost 1/3 Undead Minion
                /// </summary>
                public const string NerubianSwarmguardCore = "CORE_RLK_062";

                /// <summary>
                /// Deal $5 damage. <b>Freeze</b> all enemy minions. Summon a 5/5 Frostwyrm.<br/>
                /// 7-Cost Spell
                /// </summary>
                public const string FrostwyrmsFuryCore = "CORE_RLK_063";

                /// <summary>
                /// <b>Battlecry:</b> Spend a <b>Corpse</b> to <b>Discover</b> a Blood Rune card.<br/>
                /// 2-Cost 2/3 Minion
                /// </summary>
                public const string HematurgeCore = "CORE_RLK_066";

                /// <summary>
                /// After you cast a spell, deal 1 damage to two random enemies.<br/>
                /// 2-Cost 2/3 Elemental Minion
                /// </summary>
                public const string DeathchillerCore = "CORE_RLK_083";

                /// <summary>
                /// <b>Deathrattle:</b> Summon every minion killed by this weapon.<br/>
                /// 6-Cost Weapon
                /// </summary>
                public const string FrostmourneCore = "CORE_RLK_086";

                /// <summary>
                /// Destroy the highest Attack enemy minion.<br/>
                /// 3-Cost Spell
                /// </summary>
                public const string AsphyxiateCore = "CORE_RLK_087";

                /// <summary>
                /// <b>Battlecry:</b> If a friendly Undead died after your last turn, <b>Discover</b> an Unholy Rune card.<br/>
                /// 2-Cost 2/3 Minion
                /// </summary>
                public const string NecroticMorticianCore = "CORE_RLK_116";

                /// <summary>
                /// Summon two 2/2 Zombies with <b>Taunt</b>. Spend 4 <b>Corpses</b> to give them <b>Reborn</b>.<br/>
                /// 4-Cost Spell
                /// </summary>
                public const string TombGuardiansCore = "CORE_RLK_118";

                /// <summary>
                /// After a friendly Undead dies, draw a card.<br/>
                /// 3-Cost 2/4 Minion
                /// </summary>
                public const string AcolyteOfDeathCore = "CORE_RLK_121";

                /// <summary>
                /// Fill your board with random Undead.<br/>
                /// 9-Cost Spell
                /// </summary>
                public const string TheScourgeCorePlaceholder = "CORE_RLK_122";

                /// <summary>
                /// <b>Battlecry:</b> Spend up to 10 <b>Corpses</b> to summon a Risen Groom with <b>Taunt</b> and that much Attack and Health.<br/>
                /// 5-Cost 4/4 Undead Minion
                /// </summary>
                public const string CorpseBrideCorePlaceholder = "CORE_RLK_504";

                /// <summary>
                /// <b>Battlecry:</b> Spend up to 5 <b>Corpses</b>. Deal 2 damage to a random enemy for each.<br/>
                /// 6-Cost 5/5 Undead Minion
                /// </summary>
                public const string MarrowManipulatorCore = "CORE_RLK_505";

                /// <summary>
                /// Give all minions in your hand +1/+1. Spend 2 <b>Corpses</b> to give them +1/+1 more.<br/>
                /// 2-Cost Spell
                /// </summary>
                public const string BloodTapCore = "CORE_RLK_712";

                /// <summary>
                /// <b>Battlecry:</b> Spend up to 3 <b>Corpses</b>. <b>Freeze</b> that many enemy minions.<br/>
                /// 4-Cost Weapon
                /// </summary>
                public const string MightOfMenethilCorePlaceholder = "CORE_RLK_740";

                /// <summary>
                /// <b>Battlecry:</b> Destroy all other minions. Gain 1 <b>Corpse</b> for each enemy destroyed.<br/>
                /// 8-Cost 5/5 Undead Minion
                /// </summary>
                public const string SoulstealerCorePlaceholder = "CORE_RLK_741";

                /// <summary>
                /// <b>Reborn</b> At the end of your turn, spend 4 <b>Corpses</b> to summon a copy of this minion.<br/>
                /// 4-Cost 2/4 Undead Minion
                /// </summary>
                public const string MalignantHorrorCore = "CORE_RLK_745";

                /// <summary>
                /// <b>Magnetic</b>, <b>Reborn</b> Can <b>Magnetize</b> to Mechs or Undead.<br/>
                /// 3-Cost 3/1 Mechanical Minion
                /// </summary>
                public const string ProstheticHand = "DEEP_015";

                /// <summary>
                /// <b>Lifesteal</b>. <b>Freeze</b> any character damaged by your hero.<br/>
                /// 4-Cost Weapon
                /// </summary>
                public const string QuartziteCrusher = "DEEP_016";

                /// <summary>
                /// Summon two 1/1 Silver Hand Recruits with "<b>Deathrattle:</b> Summon a 1/1 Frail Ghoul".<br/>
                /// 2-Cost Spell
                /// </summary>
                public const string MiningCasualties = "DEEP_017";

                /// <summary>
                /// Your Leeches steal 1 more Health from their victims. <b>Battlecry:</b> Summon two 0/2 Leeches.<br/>
                /// 6-Cost 3/5 Undead/Beast Minion
                /// </summary>
                public const string HideousHusk = "EDR_810";

                /// <summary>
                /// <b>Discover</b> an Undead. Spend 2 <b>Corpses</b> to give it a <b>Dark Gift</b>.<br/>
                /// 1-Cost Spell
                /// </summary>
                public const string RiteOfAtrocity = "EDR_811";

                /// <summary>
                /// <b>Battlecry:</b> If the last card you played had an Unholy rune, gain +1 Attack. Repeat for Blood and +1 Durability.<br/>
                /// 2-Cost Weapon
                /// </summary>
                public const string GrotesqueRuneblade = "EDR_812";

                /// <summary>
                /// <b>Choose One -</b> Summon two 1/1 Ants; or Spend 2 <b>Corpses</b> to deal $4 damage to a minion.<br/>
                /// 1-Cost Spell
                /// </summary>
                public const string MorbidSwarm = "EDR_813";

                /// <summary>
                /// Deal $2 damage. Summon a 0/2 Leech.<br/>
                /// 2-Cost Spell
                /// </summary>
                public const string InfestedBreath = "EDR_814";

                /// <summary>
                /// After your opponent summons a minion, spend 2 <b>Corpses</b> to deal 3 damage to it.<br/>
                /// 3-Cost 0/5 Undead Minion
                /// </summary>
                public const string CorpseFlower = "EDR_815";

                /// <summary>
                /// At the end of your turn, give your other minions +1 Attack.<br/>
                /// 1-Cost 1/2 Beast Minion
                /// </summary>
                public const string MonstrousMosquito = "EDR_816";

                /// <summary>
                /// Draw 2 cards. Summon two 0/2 Leeches.<br/>
                /// 4-Cost Spell
                /// </summary>
                public const string SanguineInfestation = "EDR_817";

                /// <summary>
                /// <b>Taunt</b>. <b>Deathrattle:</b> Split into 1/1 Beetles. At the start of your turn, reform with any remaining.<br/>
                /// 7-Cost 7/7 Undead/Dragon Minion
                /// </summary>
                public const string Nythendra = "EDR_818";

                /// <summary>
                /// <b>Battlecry:</b> Attack ALL other minions. <b>Deathrattle:</b> Resurrect any this killed.<br/>
                /// 9-Cost 6/14 Beast Minion
                /// </summary>
                public const string Ursoc = "EDR_819";

                /// <summary>
                /// <b>Battlecry:</b> Deal 2 damage. <b>Finale:</b> To all enemies.<br/>
                /// 3-Cost 2/1 Undead Minion
                /// </summary>
                public const string HardcoreCultist = "ETC_209";

                /// <summary>
                /// <b>Lifesteal</b>. Deal ${0} damage. Summon {1} {2}/{3} Souls. <i>(Randomly improved by <b>Corpses</b> you've spent)</i><br/>
                /// 10-Cost Spell
                /// </summary>
                public const string ClimacticNecroticExplosion = "ETC_210";

                /// <summary>
                /// <b>Deathrattle:</b> Summon a 1/1 <b>Lifesteal</b> Undead. <i>(Change your Health on your turn while equipped to improve!)</i><br/>
                /// 3-Cost Weapon
                /// </summary>
                public const string ArcaniteRipper = "ETC_423";

                /// <summary>
                /// Choose a minion. Spread its <b>Deathrattle</b> to adjacent minions.<br/>
                /// 1-Cost Spell
                /// </summary>
                public const string DeathGrowl = "ETC_424";

                /// <summary>
                /// Give 4 random minions in your hand +2/+2. <i>(Swaps each turn.)</i><br/>
                /// 3-Cost Spell
                /// </summary>
                public const string HarmonicMetal = "ETC_427";

                /// <summary>
                /// <b>Battlecry:</b> Spend 5 <b>Corpses</b> to trigger and gain the <b>Deathrattle</b> of a random friendly minion that died this game.<br/>
                /// 5-Cost 5/4 Undead Minion
                /// </summary>
                public const string Boneshredder = "ETC_428";

                /// <summary>
                /// <b>Lifesteal</b> After your hero gains Health, summon a Soul with that much Attack and Health.<br/>
                /// 5-Cost 3/6 Undead Minion
                /// </summary>
                public const string ScreamingBanshee = "ETC_522";

                /// <summary>
                /// <b>Taunt</b> Costs Health instead of Mana if your hero was healed this turn.<br/>
                /// 3-Cost 3/4 Undead Minion
                /// </summary>
                public const string DeathMetalKnight = "ETC_523";

                /// <summary>
                /// <b>Deathrattle:</b> Summon a 9/9 Blight Boar with <b>Charge</b> and <b>Taunt</b>.<br/>
                /// 8-Cost 5/1 Undead Minion
                /// </summary>
                public const string CageHead = "ETC_526";

                /// <summary>
                /// Spend 3 <b>Corpses</b> to give a friendly minion <b>Reborn</b>.<br/>
                /// 2-Cost Location
                /// </summary>
                public const string MoshPit = "ETC_533";

                /// <summary>
                /// <b>Discover</b> a minion with a <b>Dark Gift</b>. It costs (2) less.<br/>
                /// 3-Cost Spell
                /// </summary>
                public const string Cremate = "FIR_900";

                /// <summary>
                /// <b>Battlecry:</b> If you're holding a minion with a <b>Dark Gift</b>, summon two 4/4 Dragons with <b>Taunt</b>.<br/>
                /// 5-Cost 4/4 Dragon Minion
                /// </summary>
                public const string FrostburnMatriarch = "FIR_901";

                /// <summary>
                /// <b>Rush, Taunt</b> <b>Battlecry:</b> Choose to spend 10, 20, or 30 <b>Corpses</b> to gain that many stats.<br/>
                /// 8-Cost 5/5 Elemental/Beast Minion
                /// </summary>
                public const string Volcoross = "FIR_951";

                /// <summary>
                /// <b><b>Spellburst</b>:</b> Trigger a random friendly minion's <b>Deathrattle</b>. <b>Starship Piece</b><br/>
                /// 2-Cost 3/2 Minion
                /// </summary>
                public const string GuidingFigure = "GDB_106";

                /// <summary>
                /// <b>Deathrattle:</b> Summon a minion with Cost equal to this minion's Attack <i>(up to 10)</i>. <b>Starship Piece</b><br/>
                /// 3-Cost 2/2 Minion
                /// </summary>
                public const string SoulboundSpire = "GDB_112";

                /// <summary>
                /// Summon a 5/5 Undead with <b>Taunt</b> and give your hero +5 Health. Spend 5 <b>Corpses</b> to do it again.<br/>
                /// 6-Cost Spell
                /// </summary>
                public const string AirlockBreach = "GDB_113";

                /// <summary>
                /// <b>Taunt</b>, <b>Reborn</b> <b>Deathrattle:</b> Resurrect a different friendly <b>Deathrattle</b> minion.<br/>
                /// 10-Cost 8/7 Minion
                /// </summary>
                public const string WakenerOfSouls = "GDB_468";

                /// <summary>
                /// After another friendly minion is <b>Reborn</b>, summon a copy of it.<br/>
                /// 1-Cost 1/3 Draenei Minion
                /// </summary>
                public const string AuchenaiDeathSpeaker = "GDB_469";

                /// <summary>
                /// <b>Battlecry:</b> The next card you play this turn costs <b>Corpses</b> instead of Mana.<br/>
                /// 6-Cost 5/5 Draenei Minion
                /// </summary>
                public const string ExarchMaladaar = "GDB_470";

                /// <summary>
                /// Give a minion <b>Taunt</b> and <b>Lifesteal</b>. If you played an adjacent card this turn, also give it <b>Reborn</b>.<br/>
                /// 1-Cost Spell
                /// </summary>
                public const string OrbitalMoon = "GDB_475";

                /// <summary>
                /// Destroy a minion. If you're building a <b>Starship</b>, also destroy a random neighbor.<br/>
                /// 4-Cost Spell
                /// </summary>
                public const string Suffocate = "GDB_476";

                /// <summary>
                /// <b>Battlecry:</b> Destroy both players' decks EXCEPT the 8 highest Cost cards in each.<br/>
                /// 8-Cost 8/8 Beast Minion
                /// </summary>
                public const string The8HandsFromBeyond = "GDB_477";

                /// <summary>
                /// <b>Discover</b> a 3-Cost <b>Deathrattle</b> minion. Summon it with <b>Reborn</b>.<br/>
                /// 3-Cost Spell
                /// </summary>
                public const string AssimilatingBlight = "GDB_478";

                /// <summary>
                /// <b>Discover</b> a <b>Temporary</b> Dark Transformation, Howling Blast, or Death Strike.<br/>
                /// 1-Cost Spell
                /// </summary>
                public const string ArthassGift = "GIFT_04";

                /// <summary>
                /// (No Text)<br/>
                /// 0-Cost Hero
                /// </summary>
                public const string TheLichKingHeroHeroSkins = "HERO_11";

                /// <summary>
                /// (No Text)<br/>
                /// 0-Cost Hero
                /// </summary>
                public const string TheLichKing_ArthasKingslayerHeroHeroSkins = "HERO_11a";

                /// <summary>
                /// (No Text)<br/>
                /// 0-Cost Hero
                /// </summary>
                public const string TheLichKing_AstroArfusHeroHeroSkins = "HERO_11aa";

                /// <summary>
                /// (No Text)<br/>
                /// 0-Cost Hero
                /// </summary>
                public const string TheLichKing_ScoutPoxiHeroHeroSkins = "HERO_11ab";

                /// <summary>
                /// (No Text)<br/>
                /// 0-Cost Hero
                /// </summary>
                public const string TheLichKing_NorthrendArthasHeroHeroSkins = "HERO_11ac";

                /// <summary>
                /// (No Text)<br/>
                /// 0-Cost Hero
                /// </summary>
                public const string TheLichKing_SoulbringerIngeHeroHeroSkins = "HERO_11ad";

                /// <summary>
                /// (No Text)<br/>
                /// 0-Cost Hero
                /// </summary>
                public const string TheLichKing_UrsocHeroHeroSkinsEnchantment = "HERO_11ae";

                /// <summary>
                /// (No Text)<br/>
                /// 0-Cost Hero
                /// </summary>
                public const string TheLichKing_PoisonScarletHeroHeroSkins = "HERO_11af";

                /// <summary>
                /// (No Text)<br/>
                /// 0-Cost Hero
                /// </summary>
                public const string TheLichKing_TheJailerHeroHeroSkins = "HERO_11ag";

                /// <summary>
                /// (No Text)<br/>
                /// 0-Cost Hero
                /// </summary>
                public const string TheLichKingHeroic_IcebloomIngeHeroHeroSkins = "HERO_11ah";

                /// <summary>
                /// (No Text)<br/>
                /// 0-Cost Hero
                /// </summary>
                public const string TheLichKing_ArachnidKerriganHeroHeroSkins = "HERO_11ai";

                /// <summary>
                /// (No Text)<br/>
                /// 0-Cost Hero
                /// </summary>
                public const string TheLichKing_KerriganHeroHeroSkins = "HERO_11aj";

                /// <summary>
                /// (No Text)<br/>
                /// 0-Cost Hero
                /// </summary>
                public const string TheLichKing_LavaLordBolvarHeroHeroSkins = "HERO_11al";

                /// <summary>
                /// (No Text)<br/>
                /// 0-Cost Hero
                /// </summary>
                public const string TheLichKing_LüBuArthasHeroHeroSkins = "HERO_11am";

                /// <summary>
                /// (No Text)<br/>
                /// 0-Cost Hero
                /// </summary>
                public const string TheLichKing_BonediggerArfusHeroHeroSkins = "HERO_11an";

                /// <summary>
                /// (No Text)<br/>
                /// 0-Cost Hero
                /// </summary>
                public const string TheLichKing_ArthasMenethilHeroHeroSkins = "HERO_11b";

                /// <summary>
                /// (No Text)<br/>
                /// 0-Cost Hero
                /// </summary>
                public const string TheLichKing_DarionMograineHeroHeroSkins = "HERO_11c";

                /// <summary>
                /// (No Text)<br/>
                /// 0-Cost Hero
                /// </summary>
                public const string TheLichKing_DaringDarionHeroHeroSkins = "HERO_11d";

                /// <summary>
                /// (No Text)<br/>
                /// 0-Cost Hero
                /// </summary>
                public const string TheLichKing_DeathMetalKingHeroHeroSkinsEnchantment = "HERO_11e";

                /// <summary>
                /// (No Text)<br/>
                /// 0-Cost Hero
                /// </summary>
                public const string TheLichKing_IngeTheIronHymnHeroHeroSkins = "HERO_11f";

                /// <summary>
                /// (No Text)<br/>
                /// 0-Cost Hero
                /// </summary>
                public const string TheLichKing_GhoulQueenScarletHeroHeroSkins = "HERO_11g";

                /// <summary>
                /// (No Text)<br/>
                /// 0-Cost Hero
                /// </summary>
                public const string CrimsonKnightSaiHeroHeroSkinsHeroic = "HERO_11h";

                /// <summary>
                /// (No Text)<br/>
                /// 0-Cost Hero
                /// </summary>
                public const string TheLichKing_FrostmongerSaiHeroHeroSkins = "HERO_11i";

                /// <summary>
                /// (No Text)<br/>
                /// 0-Cost Hero
                /// </summary>
                public const string TheLichKing_SeaReaverIngeHeroHeroSkins = "HERO_11j";

                /// <summary>
                /// (No Text)<br/>
                /// 0-Cost Hero
                /// </summary>
                public const string TheLichKing_GladiatorMograineHeroHeroSkins = "HERO_11k";

                /// <summary>
                /// (No Text)<br/>
                /// 0-Cost Hero
                /// </summary>
                public const string TheLichKing_BloodQueenLanathelHeroHeroSkins = "HERO_11l";

                /// <summary>
                /// (No Text)<br/>
                /// 0-Cost Hero
                /// </summary>
                public const string TheLichKing_FrostbringerArthasHeroHeroSkins = "HERO_11m";

                /// <summary>
                /// (No Text)<br/>
                /// 0-Cost Hero
                /// </summary>
                public const string TheLichKing_ZombieQueenScarletHeroHeroSkins = "HERO_11n";

                /// <summary>
                /// (No Text)<br/>
                /// 0-Cost Hero
                /// </summary>
                public const string TheLichKing_PitBossReskaHeroHeroSkinsEnchantment = "HERO_11o_ReskathePitBoss";

                /// <summary>
                /// (No Text)<br/>
                /// 0-Cost Hero
                /// </summary>
                public const string TheLichKing_ScourgeborneArthasHeroHeroSkins = "HERO_11p_LichKing";

                /// <summary>
                /// (No Text)<br/>
                /// 0-Cost Hero
                /// </summary>
                public const string TheLichKing_ThassarianArthasHeroHeroSkins = "HERO_11q_LichKing";

                /// <summary>
                /// (No Text)<br/>
                /// 0-Cost Hero
                /// </summary>
                public const string TheLichKing_FestiveSaiHeroHeroSkins = "HERO_11r_SaiShadestorm";

                /// <summary>
                /// (No Text)<br/>
                /// 0-Cost Hero
                /// </summary>
                public const string TheLichKing_PorcelainScarletHeroHeroSkins = "HERO_11s_Scarlet_hls";

                /// <summary>
                /// (No Text)<br/>
                /// 0-Cost Hero
                /// </summary>
                public const string TheLichKing_LanathelTheWitchHeroHeroSkinsToken = "HERO_11t_Lanathel_hls";

                /// <summary>
                /// (No Text)<br/>
                /// 0-Cost Hero
                /// </summary>
                public const string TheLichKing_ArfusHeroHeroSkins = "HERO_11u_Arfus";

                /// <summary>
                /// (No Text)<br/>
                /// 0-Cost Hero
                /// </summary>
                public const string TheLichKing_PoxiHeroHeroSkins = "HERO_11v";

                /// <summary>
                /// (No Text)<br/>
                /// 0-Cost Hero
                /// </summary>
                public const string TheLichKing_IcecreamSaiHeroHeroSkins = "HERO_11w";

                /// <summary>
                /// (No Text)<br/>
                /// 0-Cost Hero
                /// </summary>
                public const string TheLichKing_GoldpanReskaHeroHeroSkins = "HERO_11x";

                /// <summary>
                /// (No Text)<br/>
                /// 0-Cost Hero
                /// </summary>
                public const string TheLichKing_SteampunkLanathelHeroHeroSkins = "HERO_11y";

                /// <summary>
                /// (No Text)<br/>
                /// 0-Cost Hero
                /// </summary>
                public const string TheLichKing_BolvarFordragonHeroHeroSkins = "HERO_11z";

                /// <summary>
                /// <b>Battlecry:</b> Trigger a friendly minion's <b>Deathrattle</b> twice.<br/>
                /// 4-Cost 3/4 Undead Minion
                /// </summary>
                public const string YellingYodeler = "JAM_005";

                /// <summary>
                /// Enemy minions cost (5) more next turn.<br/>
                /// 2-Cost Spell
                /// </summary>
                public const string ColdFeet = "JAM_006";

                /// <summary>
                /// <b>Divine Shield</b> <b>Reborn</b><br/>
                /// 4-Cost 3/1 Undead Minion
                /// </summary>
                public const string CoolGhoul = "JAM_007";

                /// <summary>
                /// Destroy your Undead. Resummon them.<br/>
                /// 2-Cost Spell
                /// </summary>
                public const string DeadAir = "JAM_008";

                /// <summary>
                /// Deal $3 damage to a minion. If that kills it, gain a <b>Corpse</b>.<br/>
                /// 1-Cost Spell
                /// </summary>
                public const string HeartStrikeLegacy = "LEG_RLK_034";

                /// <summary>
                /// Gain 4 <b>Corpses</b>. Shuffle four Crates into your deck that summon a 2/2 Undead when drawn.<br/>
                /// 1-Cost Spell
                /// </summary>
                public const string PlaguedGrainLegacy = "LEG_RLK_039";

                /// <summary>
                /// <b>Lifesteal</b><br/>
                /// 6-Cost Weapon
                /// </summary>
                public const string CorruptedAshbringerLegacy = "LEG_RLK_067";

                /// <summary>
                /// <b>Battlecry:</b> Destroy a random minion in your opponent's hand, deck, and battlefield.<br/>
                /// 7-Cost 4/6 Undead Minion
                /// </summary>
                public const string PatchwerkLegacy = "LEG_RLK_071";

                /// <summary>
                /// <b>Battlecry:</b> Summon two 1/1 Fighters with <b>Rush</b> and <b>Reborn</b>.<br/>
                /// 5-Cost 3/3 Minion
                /// </summary>
                public const string PossessifierLegacy = "LEG_RLK_077";

                /// <summary>
                /// <b>Battlecry</b>: Deal 2 damage to an enemy and your hero.<br/>
                /// 1-Cost 1/2 Undead Minion
                /// </summary>
                public const string NoxiousCadaverLegacy = "LEG_RLK_079";

                /// <summary>
                /// <b>Battlecry:</b> Raise ALL of your <b>Corpses</b> as 1/1 Risen Golems with <b>Rush</b>. For each that can't fit, give one +2/+2.<br/>
                /// 8-Cost 9/7 Undead Minion
                /// </summary>
                public const string LordMarrowgarLegacy = "LEG_RLK_085";

                /// <summary>
                /// Draw a card. Spend 2 <b>Corpses</b> to draw another.<br/>
                /// 2-Cost Spell
                /// </summary>
                public const string DefrostLegacy = "LEG_RLK_101";

                /// <summary>
                /// Enemy characters can't be healed.<br/>
                /// 4-Cost 3/6 Undead Minion
                /// </summary>
                public const string RepulsiveGargantuanLegacy = "LEG_RLK_115";

                /// <summary>
                /// Destroy a minion. Deal 3 damage to your hero.<br/>
                /// 2-Cost Spell
                /// </summary>
                public const string ObliterateLegacy = "LEG_RLK_125";

                /// <summary>
                /// <b>Battlecry:</b> Draw 2 spells. If they're both Frost spells, deal 2 damage to all enemies.<br/>
                /// 6-Cost 3/6 Minion
                /// </summary>
                public const string OverseerFrigidaraLegacy = "LEG_RLK_224";

                /// <summary>
                /// <b>Taunt</b>. <b>Deathrattle:</b> Spend 3 <b>Corpses</b> to summon a 3/3 Risen Ymirjar with <b>Taunt</b>.<br/>
                /// 3-Cost 4/3 Undead Minion
                /// </summary>
                public const string YmirjarDeathbringerLegacy = "LEG_RLK_226";

                /// <summary>
                /// Summon two 1/1 Zombies with <b>Reborn</b>.<br/>
                /// 3-Cost Spell
                /// </summary>
                public const string GraveyardShiftLegacy = "LEG_RLK_705";

                /// <summary>
                /// After your hero attacks, reduce the Cost of a spell in your hand by (1).<br/>
                /// 3-Cost Weapon
                /// </summary>
                public const string RimefangSwordLegacy = "LEG_RLK_710";

                /// <summary>
                /// Draw a weapon. Spend a <b>Corpse</b> to reduce its Cost by (1).<br/>
                /// 1-Cost Spell
                /// </summary>
                public const string RuneforgingLegacy = "LEG_RLK_715";

                /// <summary>
                /// <b>Battlecry:</b> Summon two 2/1 Rime Elementals with "<b>Deathrattle:</b> Deal 2 damage to a random enemy."<br/>
                /// 5-Cost 4/3 Undead Minion
                /// </summary>
                public const string RimeSculptorLegacy = "LEG_RLK_752";

                /// <summary>
                /// <b>Battlecry:</b> Spend a <b>Corpse</b> to gain +1/+2.<br/>
                /// 2-Cost 2/2 Undead Minion
                /// </summary>
                public const string BonediggerGeistLegacy = "LEG_RLK_753";

                /// <summary>
                /// <b>Gigantify</b> <b>Battlecry:</b> <b>Discover</b> an Undead. Reduce its Cost by this minion's Attack.<br/>
                /// 3-Cost 2/1 Undead Minion
                /// </summary>
                public const string ToysnatchingGeist = "MIS_006";

                /// <summary>
                /// Give a minion -5/-5. Give a minion in your hand +5/+5.<br/>
                /// 4-Cost Spell
                /// </summary>
                public const string HelmOfHumiliation = "MIS_100";

                /// <summary>
                /// Whenever your hero attacks, spend 3 <b>Corpses</b> to gain +1 Durability.<br/>
                /// 5-Cost Weapon
                /// </summary>
                public const string Foamrender = "MIS_101";

                /// <summary>
                /// <b>Battlecry:</b> If you've cast three spells while holding this, <b>Freeze</b> 3 random enemy minions. <i>({0} left!)</i> <i>(Ready!)</i><br/>
                /// 3-Cost 2/3 Undead/Naga Minion
                /// </summary>
                public const string RimescaleSiren = "NX2_035";

                /// <summary>
                /// Destroy a friendly minion to summon a 4/5 Undead with <b>Rush</b>.<br/>
                /// 3-Cost Location
                /// </summary>
                public const string ConstructQuarter = "NX2_036";

                /// <summary>
                /// <b>Colossal +2</b> After an enemy minion is <b>Frozen</b>, destroy it.<br/>
                /// 7-Cost 6/6 Dragon/Undead Minion
                /// </summary>
                public const string FrostQueenSindragosa = "NX2_037";

                /// <summary>
                /// After your hero attacks and kills a minion, gain 2 <b>Corpses</b>.<br/>
                /// 3-Cost Weapon
                /// </summary>
                public const string Soulbreaker = "RLK_012";

                /// <summary>
                /// Deal $3 damage to an enemy and <b>Freeze</b> it. Deal $1 damage to all other enemies.<br/>
                /// 3-Cost Spell
                /// </summary>
                public const string HowlingBlast = "RLK_015";

                /// <summary>
                /// Deal $3 damage to a minion. If that kills it, summon a 2/2 Zombie with <b>Rush</b>.<br/>
                /// 2-Cost Spell
                /// </summary>
                public const string PlagueStrike = "RLK_018";

                /// <summary>
                /// <b>Lifesteal</b> Deal $6 damage to a minion.<br/>
                /// 4-Cost Spell
                /// </summary>
                public const string DeathStrikeCore = "RLK_024";

                /// <summary>
                /// Deal $3 damage to a minion. If that kills it, <b>Discover</b> a Frost Rune card.<br/>
                /// 2-Cost Spell
                /// </summary>
                public const string FrostStrikeCore = "RLK_025";

                /// <summary>
                /// Deal $3 damage to a minion. If that kills it, gain a <b>Corpse</b>.<br/>
                /// 1-Cost Spell
                /// </summary>
                public const string HeartStrikeCorePlaceholder = "RLK_034";

                /// <summary>
                /// Detonate a <b>Corpse</b> to deal $1 damage to all minions. If any are still alive, repeat this.<br/>
                /// 5-Cost Spell
                /// </summary>
                public const string CorpseExplosion = "RLK_035";

                /// <summary>
                /// Deal $2 damage to an enemy and <b>Freeze</b> it.<br/>
                /// 1-Cost Spell
                /// </summary>
                public const string IcyTouch = "RLK_038";

                /// <summary>
                /// Gain 4 <b>Corpses</b>. Shuffle four Crates into your deck that summon a 2/2 Undead when drawn.<br/>
                /// 1-Cost Spell
                /// </summary>
                public const string PlaguedGrainCorePlaceholder = "RLK_039";

                /// <summary>
                /// Refresh 2 Mana Crystals.<br/>
                /// 0-Cost Spell
                /// </summary>
                public const string HornOfWinter = "RLK_042";

                /// <summary>
                /// Give your minions +1/+1 and <b>Elusive</b>.<br/>
                /// 3-Cost Spell
                /// </summary>
                public const string AntiMagicShellCore = "RLK_048";

                /// <summary>
                /// Give your hero +5 Health. Spend 3 <b>Corpses</b> to gain 5 more and draw a card.<br/>
                /// 2-Cost Spell
                /// </summary>
                public const string VampiricBlood = "RLK_051";

                /// <summary>
                /// Choose an enemy minion. Your minions attack it. Resummon any that die.<br/>
                /// 2-Cost Spell
                /// </summary>
                public const string UnholyFrenzy = "RLK_056";

                /// <summary>
                /// Transform an Undead into a 4/5 Undead Monstrosity with <b>Rush</b>.<br/>
                /// 2-Cost Spell
                /// </summary>
                public const string DarkTransformation = "RLK_057";

                /// <summary>
                /// Raise up to 5 <b>Corpses</b> as 2/2 Risen Ghouls with <b>Rush</b>.<br/>
                /// 5-Cost Spell
                /// </summary>
                public const string ArmyOfTheDeadCore = "RLK_060";

                /// <summary>
                /// At the end of your turn, raise a <b>Corpse</b> as a 1/3 Risen Footman with <b>Taunt</b>.<br/>
                /// 2-Cost 2/2 Minion
                /// </summary>
                public const string BattlefieldNecromancerCore = "RLK_061";

                /// <summary>
                /// <b>Taunt</b> <b>Battlecry:</b> Summon two copies of this minion.<br/>
                /// 4-Cost 1/3 Undead Minion
                /// </summary>
                public const string NerubianSwarmguard = "RLK_062";

                /// <summary>
                /// Deal $5 damage. <b>Freeze</b> all enemy minions. Summon a 5/5 Frostwyrm.<br/>
                /// 7-Cost Spell
                /// </summary>
                public const string FrostwyrmsFury = "RLK_063";

                /// <summary>
                /// <b>Battlecry:</b> Spend a <b>Corpse</b> to <b>Discover</b> a Blood Rune card.<br/>
                /// 2-Cost 2/3 Minion
                /// </summary>
                public const string Hematurge = "RLK_066";

                /// <summary>
                /// <b>Lifesteal</b><br/>
                /// 6-Cost Weapon
                /// </summary>
                public const string CorruptedAshbringerCorePlaceholder = "RLK_067";

                /// <summary>
                /// <b>Battlecry:</b> Destroy a random minion in your opponent's hand, deck, and battlefield.<br/>
                /// 7-Cost 4/6 Undead Minion
                /// </summary>
                public const string PatchwerkCorePlaceholder = "RLK_071";

                /// <summary>
                /// <b>Battlecry:</b> Summon two 1/1 Fighters with <b>Rush</b> and <b>Reborn</b>.<br/>
                /// 5-Cost 3/3 Minion
                /// </summary>
                public const string PossessifierCorePlaceholder = "RLK_077";

                /// <summary>
                /// <b>Battlecry</b>: Deal 2 damage to an enemy and your hero.<br/>
                /// 1-Cost 1/2 Undead Minion
                /// </summary>
                public const string NoxiousCadaverCorePlaceholder = "RLK_079";

                /// <summary>
                /// <b>Taunt</b> <b>Deathrattle:</b> Return this to your hand. It costs Health instead of Mana.<br/>
                /// 5-Cost 4/6 Undead Minion
                /// </summary>
                public const string DeathbringerSaurfangCore = "RLK_082";

                /// <summary>
                /// After you cast a spell, deal 1 damage to two random enemies.<br/>
                /// 2-Cost 2/3 Elemental Minion
                /// </summary>
                public const string Deathchiller = "RLK_083";

                /// <summary>
                /// <b>Battlecry:</b> Raise ALL of your <b>Corpses</b> as 1/1 Risen Golems with <b>Rush</b>. For each that can't fit, give one +2/+2.<br/>
                /// 8-Cost 9/7 Undead Minion
                /// </summary>
                public const string LordMarrowgarCorePlaceholder = "RLK_085";

                /// <summary>
                /// <b>Deathrattle:</b> Summon every minion killed by this weapon.<br/>
                /// 6-Cost Weapon
                /// </summary>
                public const string Frostmourne = "RLK_086";

                /// <summary>
                /// Destroy the highest Attack enemy minion.<br/>
                /// 3-Cost Spell
                /// </summary>
                public const string Asphyxiate = "RLK_087";

                /// <summary>
                /// Draw a card. Spend 2 <b>Corpses</b> to draw another.<br/>
                /// 2-Cost Spell
                /// </summary>
                public const string DefrostCorePlaceholder = "RLK_101";

                /// <summary>
                /// <b>Battlecry:</b> Gain +1 Attack for each Frost spell in your hand.<br/>
                /// 1-Cost 1/2 Minion
                /// </summary>
                public const string YmirjarFrostbreaker = "RLK_110";

                /// <summary>
                /// Enemy characters can't be healed.<br/>
                /// 4-Cost 3/6 Undead Minion
                /// </summary>
                public const string RepulsiveGargantuanCorePlaceholder = "RLK_115";

                /// <summary>
                /// <b>Battlecry:</b> If a friendly Undead died after your last turn, <b>Discover</b> an Unholy Rune card.<br/>
                /// 2-Cost 2/3 Minion
                /// </summary>
                public const string NecroticMortician = "RLK_116";

                /// <summary>
                /// Summon two 2/2 Zombies with <b>Taunt</b>. Spend 4 <b>Corpses</b> to give them <b>Reborn</b>.<br/>
                /// 4-Cost Spell
                /// </summary>
                public const string TombGuardians = "RLK_118";

                /// <summary>
                /// <b>Battlecry:</b> Shred a random minion in your deck to gain 4 <b>Corpses.</b><br/>
                /// 3-Cost 3/4 Mechanical Minion
                /// </summary>
                public const string MeatGrinder = "RLK_120";

                /// <summary>
                /// After a friendly Undead dies, draw a card.<br/>
                /// 3-Cost 2/4 Minion
                /// </summary>
                public const string AcolyteOfDeath = "RLK_121";

                /// <summary>
                /// Fill your board with random Undead.<br/>
                /// 9-Cost Spell
                /// </summary>
                public const string TheScourge = "RLK_122";

                /// <summary>
                /// Destroy a minion. Deal 3 damage to your hero.<br/>
                /// 2-Cost Spell
                /// </summary>
                public const string ObliterateCorePlaceholder = "RLK_125";

                /// <summary>
                /// <b>Reborn</b> <b>Battlecry and Deathrattle:</b> Deal 2 damage to a random enemy.<br/>
                /// 4-Cost 3/3 Undead Minion
                /// </summary>
                public const string ThassarianCore = "RLK_223";

                /// <summary>
                /// <b>Battlecry:</b> Draw 2 spells. If they're both Frost spells, deal 2 damage to all enemies.<br/>
                /// 6-Cost 3/6 Minion
                /// </summary>
                public const string OverseerFrigidaraCorePlaceholder = "RLK_224";

                /// <summary>
                /// <b>Battlecry:</b> Infect all enemy minions. When they die, you summon a 2/2 Zombie with <b>Taunt</b>.<br/>
                /// 3-Cost 3/3 Beast Minion
                /// </summary>
                public const string Blightfang = "RLK_225";

                /// <summary>
                /// <b>Taunt</b>. <b>Deathrattle:</b> Spend 3 <b>Corpses</b> to summon a 3/3 Risen Ymirjar with <b>Taunt</b>.<br/>
                /// 3-Cost 4/3 Undead Minion
                /// </summary>
                public const string YmirjarDeathbringerCorePlaceholder = "RLK_226";

                /// <summary>
                /// <b>Battlecry</b>: Gain a <b>Corpse</b>.<br/>
                /// 1-Cost 1/3 Undead Minion
                /// </summary>
                public const string BodyBaggerCore = "RLK_503";

                /// <summary>
                /// <b>Battlecry:</b> Spend up to 10 <b>Corpses</b> to summon a Risen Groom with <b>Taunt</b> and that much Attack and Health.<br/>
                /// 5-Cost 4/4 Undead Minion
                /// </summary>
                public const string CorpseBride = "RLK_504";

                /// <summary>
                /// <b>Battlecry:</b> Spend up to 5 <b>Corpses</b>. Deal 2 damage to a random enemy for each.<br/>
                /// 6-Cost 5/5 Undead Minion
                /// </summary>
                public const string MarrowManipulator = "RLK_505";

                /// <summary>
                /// <b>Taunt</b> <b>Battlecry:</b> Raise up to 6 <b>Corpses</b> as 1/3 Risen Footmen with <b>Taunt</b>.<br/>
                /// 8-Cost 8/8 Undead Minion
                /// </summary>
                public const string BoneguardCommander = "RLK_506";

                /// <summary>
                /// <b>Deathrattle:</b> Draw a Frost spell.<br/>
                /// 2-Cost 3/2 Undead Minion
                /// </summary>
                public const string HarbingerOfWinterCore = "RLK_511";

                /// <summary>
                /// Deal $4 damage. Your next spell this turn costs (2) less.<br/>
                /// 3-Cost Spell
                /// </summary>
                public const string GlacialAdvance = "RLK_512";

                /// <summary>
                /// After your hero attacks a minion, deal 2 damage to the enemy hero.<br/>
                /// 1-Cost Weapon
                /// </summary>
                public const string BoneBreaker = "RLK_516";

                /// <summary>
                /// Summon two 1/1 Zombies with <b>Reborn</b>.<br/>
                /// 3-Cost Spell
                /// </summary>
                public const string GraveyardShiftCorePlaceholder = "RLK_705";

                /// <summary>
                /// <b>Battlecry:</b> For the rest of the game, deal 3 damage to your opponent at the end of your turns.<br/>
                /// 7-Cost 7/7 Undead Minion
                /// </summary>
                public const string AlexandrosMograine = "RLK_706";

                /// <summary>
                /// Give your minions +1 Attack. Spend 5 <b>Corpses</b> to give them +3 instead.<br/>
                /// 4-Cost Spell
                /// </summary>
                public const string GraveStrengthCore = "RLK_707";

                /// <summary>
                /// <b>Battlecry and Deathrattle:</b> Draw a card.<br/>
                /// 3-Cost 2/2 Undead/Draenei Minion
                /// </summary>
                public const string ChillfallenBaronCore = "RLK_708";

                /// <summary>
                /// Deal $2 damage to all enemies. Draw a card.<br/>
                /// 4-Cost Spell
                /// </summary>
                public const string RemorselessWinterCore = "RLK_709";

                /// <summary>
                /// After your hero attacks, reduce the Cost of a spell in your hand by (1).<br/>
                /// 3-Cost Weapon
                /// </summary>
                public const string RimefangSwordCorePlaceholder = "RLK_710";

                /// <summary>
                /// <b>Battlecry:</b> Give a minion in your hand Attack equal to this minion's Attack.<br/>
                /// 2-Cost 3/2 Beast Minion
                /// </summary>
                public const string ViciousBloodworm = "RLK_711";

                /// <summary>
                /// Give all minions in your hand +1/+1. Spend 2 <b>Corpses</b> to give them +1/+1 more.<br/>
                /// 2-Cost Spell
                /// </summary>
                public const string BloodTap = "RLK_712";

                /// <summary>
                /// <b>Deathrattle:</b> Copy all Frost spells in your hand.<br/>
                /// 4-Cost 4/3 Undead Minion
                /// </summary>
                public const string LadyDeathwhisper = "RLK_713";

                /// <summary>
                /// Draw a weapon. Spend a <b>Corpse</b> to reduce its Cost by (1).<br/>
                /// 1-Cost Spell
                /// </summary>
                public const string RuneforgingCorePlaceholder = "RLK_715";

                /// <summary>
                /// <b>Taunt</b>, <b>Lifesteal</b> At the end of your turn, attack the lowest Health enemy.<br/>
                /// 6-Cost 5/6 Undead Minion
                /// </summary>
                public const string GnomeMuncherCore = "RLK_720";

                /// <summary>
                /// <b>Lifesteal</b> Infect all enemy minions. At the end of your turns, they take 2 damage.<br/>
                /// 5-Cost Spell
                /// </summary>
                public const string BloodBoil = "RLK_730";

                /// <summary>
                /// <b>Battlecry:</b> Spend 2 <b>Corpses</b> to give all minions in your hand +2 Attack.<br/>
                /// 3-Cost 2/5 Undead Minion
                /// </summary>
                public const string DarkfallenNeophyte = "RLK_731";

                /// <summary>
                /// <b>Battlecry:</b> Spend up to 3 <b>Corpses</b>. <b>Freeze</b> that many enemy minions.<br/>
                /// 4-Cost Weapon
                /// </summary>
                public const string MightOfMenethil = "RLK_740";

                /// <summary>
                /// <b>Battlecry:</b> Destroy all other minions. Gain 1 <b>Corpse</b> for each enemy destroyed.<br/>
                /// 8-Cost 5/5 Undead Minion
                /// </summary>
                public const string Soulstealer = "RLK_741";

                /// <summary>
                /// Costs (1) less for each <b>Corpse</b> you've spent this game.<br/>
                /// 9-Cost 8/8 Undead Minion
                /// </summary>
                public const string StitchedGiantCore = "RLK_744";

                /// <summary>
                /// <b>Reborn</b> At the end of your turn, spend 4 <b>Corpses</b> to summon a copy of this minion.<br/>
                /// 4-Cost 2/4 Undead Minion
                /// </summary>
                public const string MalignantHorror = "RLK_745";

                /// <summary>
                /// <b>Battlecry:</b> Summon two 2/1 Rime Elementals with "<b>Deathrattle:</b> Deal 2 damage to a random enemy."<br/>
                /// 5-Cost 4/3 Undead Minion
                /// </summary>
                public const string RimeSculptorCorePlaceholder = "RLK_752";

                /// <summary>
                /// <b>Battlecry:</b> Spend a <b>Corpse</b> to gain +1/+2.<br/>
                /// 2-Cost 2/2 Undead Minion
                /// </summary>
                public const string BonediggerGeistCorePlaceholder = "RLK_753";

                /// <summary>
                /// <b>Battlecry:</b> Give a friendly Undead +2 Attack.<br/>
                /// Tier-1 1/2 Undead Minion
                /// </summary>
                public const string SkeletalSidekickCore = "RLK_958";

                /// <summary>
                /// Get a 1/1 Baneling that explodes. If you control a Zerg minion, get another Baneling.<br/>
                /// 1-Cost Spell
                /// </summary>
                public const string BanelingBarrage = "SC_001";

                /// <summary>
                /// <b>Deathrattle:</b> Your Zerg minions have +1 Attack for the rest of the game.<br/>
                /// 3-Cost 4/2 Minion
                /// </summary>
                public const string Infestor = "SC_002";

                /// <summary>
                /// <b>Battlecry:</b> Summon a minion from your opponent's hand. Your other Zerg minions gain <b>Reborn</b> and attack it.<br/>
                /// 4-Cost 5/3 Minion
                /// </summary>
                public const string Viper = "SC_018";

                /// <summary>
                /// <b>Deathrattle:</b> Deal 6 damage to three random enemies.<br/>
                /// 6-Cost 6/3 Undead/Beast Minion
                /// </summary>
                public const string BonechillStegodon = "TLC_401";

                /// <summary>
                /// <b>Battlecry:</b> Draw a <b>Deathrattle</b> minion that costs (3) or less. <b>Kindred:</b> It costs (0).<br/>
                /// 4-Cost 3/4 Undead/Beast Minion
                /// </summary>
                public const string DreadRaptor = "TLC_432";

                /// <summary>
                /// <b>Quest:</b> Spend 18 <b>Corpses</b>. <b>Reward:</b> Tyrax, Bone Terror.<br/>
                /// 1-Cost Spell
                /// </summary>
                public const string ReanimateTheTerror = "TLC_433";

                /// <summary>
                /// <b>Discover</b> an Undead. Spend 5 <b>Corpses</b> to keep all 3 instead.<br/>
                /// 3-Cost Spell
                /// </summary>
                public const string Paleomancy = "TLC_434";

                /// <summary>
                /// <b>Discover</b> a Frost Rune card. If you play it this turn, also pick one of the others.<br/>
                /// 1-Cost Spell
                /// </summary>
                public const string CryptMap = "TLC_435";

                /// <summary>
                /// <b><b>Rush</b>, Lifesteal</b> Costs <b>Corpses</b> instead of Mana.<br/>
                /// 5-Cost 4/3 Undead/Beast Minion
                /// </summary>
                public const string ReanimatedPterrordax = "TLC_436";

                /// <summary>
                /// Deal $2 damage to all enemy minions. Enemy minions cost (2) more next turn.<br/>
                /// 4-Cost Spell
                /// </summary>
                public const string WaveOfTar = "TLC_439";

                /// <summary>
                /// Deal $4 damage and draw a card. <b>Kindred: </b>Draw another.<br/>
                /// 4-Cost Spell
                /// </summary>
                public const string Cryosleep = "TLC_440";

                /// <summary>
                /// <b>Reborn</b> <b>Deathrattle:</b> Summon a 2/2 Undead Beast with <b>Taunt</b>.<br/>
                /// 3-Cost 1/1 Minion
                /// </summary>
                public const string ReluctantWrangler = "TLC_443";

                /// <summary>
                /// <b>Battlecry:</b> Summon two <b>Deathrattle</b> minions from your deck. They fight!<br/>
                /// 8-Cost 8/6 Minion
                /// </summary>
                public const string HighCultistHerenn = "TLC_810";

                /// <summary>
                /// <b>Rush</b> After you cast a Frost spell, gain <b>Reborn</b>.<br/>
                /// 3-Cost 4/2 Undead/Beast Minion
                /// </summary>
                public const string RambunctiousStuffy = "TOY_821";

                /// <summary>
                /// Choose a friendly minion. <b>Discover</b> a spell that costs (4) or less for it to cast when it dies.<br/>
                /// 2-Cost Spell
                /// </summary>
                public const string SilkStitching = "TOY_822";

                /// <summary>
                /// <b>Battlecry:</b> If your deck started with a Blood, Frost, or Unholy card, gain <b>Lifesteal</b>, <b>Reborn</b>, or <b>Rush</b> respectively.<br/>
                /// 3-Cost 3/3 Undead Minion
                /// </summary>
                public const string RainbowSeamstress = "TOY_823";

                /// <summary>
                /// At the end of your turn, deal this minion's Attack damage randomly split among enemies.<br/>
                /// 4-Cost 2/4 Undead/Quilboar Minion
                /// </summary>
                public const string DarkthornQuilter = "TOY_824";

                /// <summary>
                /// Give Undead in your hand +1/+1. <i>(Gain |4(<b>Corpse</b>, <b>Corpses</b>) to upgrade.)</i><br/>
                /// 1-Cost Spell
                /// </summary>
                public const string LesserSpinelSpellstone = "TOY_825";

                /// <summary>
                /// Give all minions "<b>Deathrattle:</b> Deal 1 damage to all minions."<br/>
                /// 3-Cost Spell
                /// </summary>
                public const string ThreadsOfDespair = "TOY_826";

                /// <summary>
                /// <b>Taunt</b> <b>Battlecry:</b> Spend 5 <b>Corpses</b> to summon a copy of this.<br/>
                /// 2-Cost 3/2 Undead/Mechanical Minion
                /// </summary>
                public const string ShamblingZombietank = "TOY_827";

                /// <summary>
                /// <b>Miniaturize</b>, <b>Taunt</b> <b>Deathrattle:</b> Give Undead in your hand +2/+2.<br/>
                /// 5-Cost 2/6 Undead Minion
                /// </summary>
                public const string AmateurPuppeteer = "TOY_828";

                /// <summary>
                /// <b>Battlecry:</b> Destroy the enemy minion with the most <i>Attack!</i> Shuffle my Head into your deck, you must get it <i>back!</i><br/>
                /// 6-Cost Hero
                /// </summary>
                public const string TheHeadlessHorseman = "TOY_829";

                /// <summary>
                /// <b>Battlecry:</b> <b>Discover</b> a 5, 3, and 1-Cost minion to stitch to this. <b>Deathrattle:</b> Summon the 5-Cost minion.<br/>
                /// 6-Cost 6/4 Undead Minion
                /// </summary>
                public const string DrStitchensew = "TOY_830";

                /// <summary>
                /// <b>Deathrattle:</b> Shuffle two random Plagues into your opponent's deck.<br/>
                /// 2-Cost 3/2 Undead Minion
                /// </summary>
                public const string DistressedKvaldir = "TTN_450";

                /// <summary>
                /// Deal $3 damage. Shuffle two random Plagues into your opponent's deck.<br/>
                /// 2-Cost Spell
                /// </summary>
                public const string DownWithTheShip = "TTN_454";

                /// <summary>
                /// <b>Battlecry:</b> Destroy a Plague in your opponent's deck to deal 3 damage to all enemy minions.<br/>
                /// 4-Cost 4/3 Minion
                /// </summary>
                public const string TombTraitor = "TTN_455";

                /// <summary>
                /// <b>Battlecry:</b> Spend 3 <b>Corpses</b> to deal 3 damage. <b>Forge:</b> Gain them instead.<br/>
                /// 3-Cost 3/3 Undead Minion
                /// </summary>
                public const string Eulogizer = "TTN_457";

                /// <summary>
                /// <b><b>Rush</b>, Reborn</b> Costs (1) less for each Plague shuffled into the enemy deck this game.<br/>
                /// 11-Cost 8/5 Minion
                /// </summary>
                public const string ChainedGuardian = "TTN_459";

                /// <summary>
                /// <b>Discover</b> a spell from your deck. If it's a Frost spell, <b>Freeze</b> a random enemy minion.<br/>
                /// 2-Cost Spell
                /// </summary>
                public const string NorthernNavigation = "TTN_735";

                /// <summary>
                /// After your hero attacks, shuffle a random Plague into your opponent's deck.<br/>
                /// 1-Cost Weapon
                /// </summary>
                public const string StaffOfThePrimus = "TTN_736";

                /// <summary>
                /// <b>Titan</b> After this uses an ability, <b>Discover</b> a card with that Rune.<br/>
                /// 8-Cost 7/9 Minion
                /// </summary>
                public const string ThePrimus = "TTN_737";

                /// <summary>
                /// Both players draw 2 cards. Your opponent can not play them next turn.<br/>
                /// 2-Cost Spell
                /// </summary>
                public const string FrozenOver = "TTN_744";

                /// <summary>
                /// <b>Battlecry:</b> Shuffle all three Plagues into your opponent's deck. Plagues they draw this game are unending.<br/>
                /// 4-Cost 4/4 Minion
                /// </summary>
                public const string Helya = "TTN_850";

                /// <summary>
                /// <b><b>Deathrattle:</b> Freeze</b> 3 random enemies. Any that were already <b>Frozen</b> take 5 damage instead.<br/>
                /// 3-Cost 2/2 Undead/Pirate Minion
                /// </summary>
                public const string FrostbittenFreebooter = "VAC_402";

                /// <summary>
                /// Deal 3 damage randomly split among all enemies. After a friendly minion dies, reopen this.<br/>
                /// 4-Cost Location
                /// </summary>
                public const string HorizonsEdge = "VAC_425";

                /// <summary>
                /// <b>Deathrattle:</b> For the rest of the game, your minions have +1 Attack.<br/>
                /// 4-Cost 4/3 Pirate/Undead Minion
                /// </summary>
                public const string ElizaGoreblade = "VAC_426";

                /// <summary>
                /// Deal $3 damage. Spend 3 <b>Corpses</b> to return this to your hand at the end of your turn.<br/>
                /// 2-Cost Spell
                /// </summary>
                public const string Corpsicle = "VAC_427";

                /// <summary>
                /// Costs (1) if a character is <b>Frozen</b>.<br/>
                /// 4-Cost 4/4 Undead Minion
                /// </summary>
                public const string SnowShredder = "VAC_429";

                /// <summary>
                /// Whenever you play a <b>Deathrattle</b> minion, give it <b>Reborn</b>.<br/>
                /// 2-Cost 1/4 Undead/Pirate Minion
                /// </summary>
                public const string BrittleboneBuccaneer = "VAC_436";

                /// <summary>
                /// <b>Shaman Tourist</b> <b>Battlecry:</b> Draw a spell of each spell school.<br/>
                /// 4-Cost 4/4 Undead Minion
                /// </summary>
                public const string Buttons = "VAC_437";

                /// <summary>
                /// Summon five 1/1 Ghouls that attack random enemies.<br/>
                /// 4-Cost Spell
                /// </summary>
                public const string GhoulsNight = "VAC_445";

                /// <summary>
                /// <b>Freeze</b> a character. Draw a card for each <b>Frozen</b> character.<br/>
                /// 2-Cost Spell
                /// </summary>
                public const string SlipperySlope = "VAC_513";

                /// <summary>
                /// <b>Rush</b> <b>Deathrattle:</b> Summon a 1/1 Dreadhound with <b>Reborn</b>.<br/>
                /// 2-Cost 2/1 Pirate/Undead Minion
                /// </summary>
                public const string DreadhoundHandler = "VAC_514";

                /// <summary>
                /// <b>Taunt</b>. <b>Deathrattle:</b> Summon a random 8-Cost minion.<br/>
                /// 6-Cost 2/2 Undead Minion
                /// </summary>
                public const string TravelSecurity = "WORK_010";

                /// <summary>
                /// Give ALL minions <b>Reborn</b>, then destroy all minions.<br/>
                /// 4-Cost Spell
                /// </summary>
                public const string EternalLayover = "WORK_028";

                /// <summary>
                /// <b>Discover</b> a card from your deck. Spend 5 <b>Corpses</b> to copy it.<br/>
                /// 2-Cost Spell
                /// </summary>
                public const string SoulSearching = "WORK_070";

                /// <summary>
                /// <b>Battlecry:</b> <b>Excavate</b> a treasure. It costs (0).<br/>
                /// 4-Cost 3/3 Undead Minion
                /// </summary>
                public const string SkeletonCrew = "WW_322";

                /// <summary>
                /// <b>Deathrattle:</b> The next time you <b>Excavate</b>, resummon this.<br/>
                /// 2-Cost 2/1 Undead Minion
                /// </summary>
                public const string PileOfBones = "WW_324";

                /// <summary>
                /// Deal $3 damage. <b>Excavate</b> a treasure.<br/>
                /// 3-Cost Spell
                /// </summary>
                public const string ReapWhatYouSow = "WW_352";

                /// <summary>
                /// Deal damage to a minion equal to your <b>Corpses</b>.<br/>
                /// 1-Cost Spell
                /// </summary>
                public const string FistfulOfCorpses = "WW_354";

                /// <summary>
                /// <b>Taunt</b> <b>Battlecry:</b> If you've <b>Excavated</b> twice, your next card this turn costs (7) less.<br/>
                /// 7-Cost 7/7 Undead/Beast Minion
                /// </summary>
                public const string HarrowingOx = "WW_356";

                /// <summary>
                /// At the end of your turn, gain 5 <b>Corpses</b>. At the start of your turn, spend 5 <b>Corpses</b> to give your hero +5 Health.<br/>
                /// 4-Cost 2/8 Undead Minion
                /// </summary>
                public const string MawAndPaw = "WW_357";

                /// <summary>
                /// <b>Battlecry:</b> <b>Discover</b> an Undead. <b>Quickdraw:</b> It costs (2) less.<br/>
                /// 3-Cost 4/3 Undead Minion
                /// </summary>
                public const string FarmHand = "WW_358";

                /// <summary>
                /// Summon four 1/1 Undead with <b>Rush</b> that die at the end of turn.<br/>
                /// 3-Cost Spell
                /// </summary>
                public const string CropRotation = "WW_368";

                /// <summary>
                /// <b>Rush</b>. Costs (1) less for each minion that died this game. <b>Deathrattle:</b> Take control of a random enemy minion.<br/>
                /// 20-Cost 6/3 Undead Minion
                /// </summary>
                public const string ReskaThePitBoss = "WW_373";

                /// <summary>
                /// Spend up to 8 <b>Corpses</b> to summon a random minion of that Cost.<br/>
                /// 3-Cost Spell
                /// </summary>
                public const string CorpseFarm = "WW_374";

                /// <summary>
                /// <b>Discover</b> a weapon. Spend 3 <b>Corpses</b> to give it +1/+1.<br/>
                /// 1-Cost Spell
                /// </summary>
                public const string RunesOfDarkness = "YOG_511";

                /// <summary>
                /// After you summon an Undead, give it <b>Poisonous</b>.<br/>
                /// 3-Cost 2/4 Undead Minion
                /// </summary>
                public const string SicklyGrimewalker = "YOG_512";

                /// <summary>
                /// Give a friendly Undead +2/+2. Spend 5 <b>Corpses</b> to summon a copy of it.<br/>
                /// 4-Cost Spell
                /// </summary>
                public const string SinisterSoulcage = "YOG_513";
            }
        }
    }
}