namespace HearthDb
{
    /* THIS CLASS WAS GENERATED BY HearthDb.CardIdGenerator. DO NOT EDIT. */
    public partial class CardIds
    {
        public partial class NonCollectible
        {
            public class DreamCards
            {
                /// <summary>
                /// <b>Elusive</b><br/>
                /// 2-Cost 3/5 Minion
                /// </summary>
                public const string LaughingSister = "DREAM_01";

                /// <summary>
                /// Deal $5 damage to all characters except Ysera.<br/>
                /// 2-Cost Spell
                /// </summary>
                public const string YseraAwakens = "DREAM_02";

                /// <summary>
                /// (No Text)<br/>
                /// 4-Cost 7/6 Dragon Minion
                /// </summary>
                public const string EmeraldDrake = "DREAM_03";

                /// <summary>
                /// Return a minion to its owner's hand.<br/>
                /// 0-Cost Spell
                /// </summary>
                public const string Dream = "DREAM_04";

                /// <summary>
                /// Give a minion +5/+5. At the start of your next turn, destroy it.<br/>
                /// 0-Cost Spell
                /// </summary>
                public const string NightmareExpert1 = "DREAM_05";

                /// <summary>
                /// <b>Deathrattle:</b> Draw a card.<br/>
                /// Enchantment
                /// </summary>
                public const string RepurposedEnchantmentTavernBrawl = "TB_MP_02e";

                /// <summary>
                /// <b>Elusive</b><br/>
                /// 2-Cost 3/5 Minion
                /// </summary>
                public const string LaughingSisterVanilla = "VAN_DREAM_01";

                /// <summary>
                /// Deal $5 damage to all characters except Ysera.<br/>
                /// 2-Cost Spell
                /// </summary>
                public const string YseraAwakensVanilla = "VAN_DREAM_02";

                /// <summary>
                /// (No Text)<br/>
                /// 4-Cost 7/6 Dragon Minion
                /// </summary>
                public const string EmeraldDrakeVanilla = "VAN_DREAM_03";

                /// <summary>
                /// Return a minion to its owner's hand.<br/>
                /// 0-Cost Spell
                /// </summary>
                public const string DreamVanilla = "VAN_DREAM_04";

                /// <summary>
                /// Give a minion +5/+5. At the start of your next turn, destroy it.<br/>
                /// 0-Cost Spell
                /// </summary>
                public const string NightmareVanilla = "VAN_DREAM_05";

                /// <summary>
                /// Give a minion <b>Immune</b> this turn and +5/+5.<br/>
                /// 0-Cost Spell
                /// </summary>
                public const string Shaladrassil_CorruptedNightmareToken = "EDR_846t1";

                /// <summary>
                /// Shuffle a minion into its owner's deck.<br/>
                /// 0-Cost Spell
                /// </summary>
                public const string Shaladrassil_CorruptedDreamToken = "EDR_846t2";

                /// <summary>
                /// <b>Elusive</b> Your hero is <b>Elusive</b>.<br/>
                /// 2-Cost 6/10 Minion
                /// </summary>
                public const string Shaladrassil_CorruptedLaughingSisterToken = "EDR_846t3";

                /// <summary>
                /// Deal $5 damage to all enemies. <i>(ESPECIALLY Ysera!)</i><br/>
                /// 2-Cost Spell
                /// </summary>
                public const string Shaladrassil_CorruptedAwakeningToken = "EDR_846t4";

                /// <summary>
                /// (No Text)<br/>
                /// 4-Cost 14/12 Dragon Minion
                /// </summary>
                public const string Shaladrassil_CorruptedDrakeToken = "EDR_846t5";
            }
        }
    }
}