namespace HearthDb
{
    /* THIS CLASS WAS GENERATED BY HearthDb.CardIdGenerator. DO NOT EDIT. */
    public partial class CardIds
    {
        public partial class NonCollectible
        {
            public class Deathknight
            {
                /// <summary>
                /// <b>Hero Power</b> Summon a 2/1 Ghoul with <b>Charge</b>. It dies at end of turn.<br/>
                /// 2-Cost HeroPower
                /// </summary>
                public const string TheLichKingHeroic_GhoulFrenzyEnchantment = "HERO_11aehp2";

                /// <summary>
                /// <b>Hero Power</b> Summon a 2/1 Ghoul with <b>Charge</b>. It dies at end of turn.<br/>
                /// 2-Cost HeroPower
                /// </summary>
                public const string TheLichKing_GhoulFrenzy1 = "HERO_11aghp2";

                /// <summary>
                /// <b>Hero Power</b> Summon a 2/1 Ghoul with <b>Charge</b>. It dies at end of turn.<br/>
                /// 2-Cost HeroPower
                /// </summary>
                public const string TheLichKing_GhoulFrenzy2 = "HERO_11aihp2";

                /// <summary>
                /// <b>Hero Power</b> Summon a 2/1 Ghoul with <b>Charge</b>. It dies at end of turn.<br/>
                /// 2-Cost HeroPower
                /// </summary>
                public const string TheLichKing_GhoulFrenzy3 = "HERO_11ajhp2";

                /// <summary>
                /// <b>Hero Power</b> Summon a 1/1 Ghoul with <b>Charge</b>. It dies at end of turn.<br/>
                /// 2-Cost HeroPower
                /// </summary>
                public const string TheLichKing_GhoulCharge = "HERO_11bp";

                /// <summary>
                /// <b>Hero Power</b> Summon a 2/1 Ghoul with <b>Charge</b>. It dies at end of turn.<br/>
                /// 2-Cost HeroPower
                /// </summary>
                public const string TheLichKing_GhoulFrenzy4 = "HERO_11bp2";

                /// <summary>
                /// <b>Charge</b> At the end of your turn, this minion dies.<br/>
                /// 1-Cost 2/1 Undead Minion
                /// </summary>
                public const string TheLichKing_FrenziedGhoul = "HERO_11bp2t";

                /// <summary>
                /// <b>Charge</b> At the end of your turn, this minion dies.<br/>
                /// 1-Cost 1/1 Undead Minion
                /// </summary>
                public const string TheLichKing_FrailGhoul = "HERO_11bpt";

                /// <summary>
                /// <b>Hero Power</b> Summon a 2/1 Ghoul with <b>Charge</b>. It dies at end of turn.<br/>
                /// 2-Cost HeroPower
                /// </summary>
                public const string TheLichKing_GhoulFrenzy5 = "HERO_11cbp2";

                /// <summary>
                /// <b>Hero Power</b> Summon a 2/1 Ghoul with <b>Charge</b>. It dies at end of turn.<br/>
                /// 2-Cost HeroPower
                /// </summary>
                public const string TheLichKing_GhoulFrenzy6 = "HERO_11gbp2";

                /// <summary>
                /// <b>Hero Power</b> Summon a 2/1 Ghoul with <b>Charge</b>. It dies at end of turn.<br/>
                /// 2-Cost HeroPower
                /// </summary>
                public const string CrimsonKnightSaiHeroic_GhoulFrenzy = "HERO_11hbp2";

                /// <summary>
                /// <b>Hero Power</b> Summon a 2/1 Ghoul with <b>Charge</b>. It dies at end of turn.<br/>
                /// 2-Cost HeroPower
                /// </summary>
                public const string TheLichKing_GhoulFrenzy7 = "HERO_11ibp2";

                /// <summary>
                /// <b>Hero Power</b> Summon a 2/1 Ghoul with <b>Charge</b>. It dies at end of turn.<br/>
                /// 2-Cost HeroPower
                /// </summary>
                public const string TheLichKing_GhoulFrenzyEnchantment = "HERO_11ohp2";

                /// <summary>
                /// <b>Hero Power</b> Summon a 2/1 Ghoul with <b>Charge</b>. It dies at end of turn.<br/>
                /// 2-Cost HeroPower
                /// </summary>
                public const string TheLichKing_GhoulFrenzy8 = "HERO_11uhp2";

                /// <summary>
                /// <b>Hero Power</b> Summon a 2/1 Ghoul with <b>Charge</b>. It dies at end of turn.<br/>
                /// 2-Cost HeroPower
                /// </summary>
                public const string TheLichKing_GhoulFrenzy9 = "HERO_11vhp2";

                /// <summary>
                /// <b>Hero Power</b> Summon a 2/1 Ghoul with <b>Charge</b>. It dies at end of turn.<br/>
                /// 2-Cost HeroPower
                /// </summary>
                public const string TheLichKing_GhoulFrenzy10 = "HERO_11zhp2";

                /// <summary>
                /// <b>Hero Power</b> Summon a 1/1 Ghoul with <b>Charge</b>. It dies at end of turn.<br/>
                /// 2-Cost HeroPower
                /// </summary>
                public const string TheLichKingHeroic_GhoulChargeHeroSkinsEnchantment = "HERO_11aehp";

                /// <summary>
                /// <b>Hero Power</b> Summon a 1/1 Ghoul with <b>Charge</b>. It dies at end of turn.<br/>
                /// 2-Cost HeroPower
                /// </summary>
                public const string TheLichKing_GhoulChargeHeroSkins1 = "HERO_11aghp";

                /// <summary>
                /// <b>Hero Power</b> Summon a 1/1 Ghoul with <b>Charge</b>. It dies at end of turn.<br/>
                /// 2-Cost HeroPower
                /// </summary>
                public const string TheLichKing_GhoulChargeHeroSkins2 = "HERO_11aihp";

                /// <summary>
                /// <b>Hero Power</b> Summon a 1/1 Ghoul with <b>Charge</b>. It dies at end of turn.<br/>
                /// 2-Cost HeroPower
                /// </summary>
                public const string TheLichKing_GhoulChargeHeroSkins3 = "HERO_11ajhp";

                /// <summary>
                /// <b>Hero Power</b> Summon a 1/1 Ghoul with <b>Charge</b>. It dies at end of turn.<br/>
                /// 2-Cost HeroPower
                /// </summary>
                public const string TheLichKing_GhoulChargeHeroSkins4 = "HERO_11cbp";

                /// <summary>
                /// <b>Hero Power</b> Summon a 1/1 Ghoul with <b>Charge</b>. It dies at end of turn.<br/>
                /// 2-Cost HeroPower
                /// </summary>
                public const string TheLichKing_GhoulChargeHeroSkins5 = "HERO_11fbp";

                /// <summary>
                /// <b>Hero Power</b> Summon a 2/1 Ghoul with <b>Charge</b>. It dies at end of turn.<br/>
                /// 2-Cost HeroPower
                /// </summary>
                public const string TheLichKing_GhoulFrenzyHeroSkins1 = "HERO_11fbp2";

                /// <summary>
                /// <b>Hero Power</b> Summon a 1/1 Ghoul with <b>Charge</b>. It dies at end of turn.<br/>
                /// 2-Cost HeroPower
                /// </summary>
                public const string TheLichKing_GhoulChargeHeroSkins6 = "HERO_11gbp";

                /// <summary>
                /// <b>Hero Power</b> Summon a 1/1 Ghoul with <b>Charge</b>. It dies at end of turn.<br/>
                /// 2-Cost HeroPower
                /// </summary>
                public const string CrimsonKnightSaiHeroic_GhoulChargeHeroSkins = "HERO_11hbp";

                /// <summary>
                /// <b>Hero Power</b> Summon a 1/1 Ghoul with <b>Charge</b>. It dies at end of turn.<br/>
                /// 2-Cost HeroPower
                /// </summary>
                public const string TheLichKing_GhoulChargeHeroSkins7 = "HERO_11ibp";

                /// <summary>
                /// <b>Hero Power</b> Summon a 1/1 Ghoul with <b>Charge</b>. It dies at end of turn.<br/>
                /// 2-Cost HeroPower
                /// </summary>
                public const string TheLichKing_GhoulChargeHeroSkins8 = "HERO_11lbp";

                /// <summary>
                /// <b>Hero Power</b> Summon a 2/1 Ghoul with <b>Charge</b>. It dies at end of turn.<br/>
                /// 2-Cost HeroPower
                /// </summary>
                public const string TheLichKing_GhoulFrenzyHeroSkins2 = "HERO_11lbp2";

                /// <summary>
                /// <b>Hero Power</b> Summon a 1/1 Ghoul with <b>Charge</b>. It dies at end of turn.<br/>
                /// 2-Cost HeroPower
                /// </summary>
                public const string TheLichKing_GhoulChargeHeroSkinsEnchantment = "HERO_11ohp";

                /// <summary>
                /// <b>Hero Power</b> Summon a 1/1 Ghoul with <b>Charge</b>. It dies at end of turn.<br/>
                /// 2-Cost HeroPower
                /// </summary>
                public const string TheLichKing_GhoulChargeHeroSkins9 = "HERO_11uhp";

                /// <summary>
                /// <b>Hero Power</b> Summon a 1/1 Ghoul with <b>Charge</b>. It dies at end of turn.<br/>
                /// 2-Cost HeroPower
                /// </summary>
                public const string TheLichKing_GhoulChargeHeroSkins10 = "HERO_11vhp";

                /// <summary>
                /// <b>Hero Power</b> Summon a 1/1 Ghoul with <b>Charge</b>. It dies at end of turn.<br/>
                /// 2-Cost HeroPower
                /// </summary>
                public const string TheLichKing_GhoulChargeHeroSkins11 = "HERO_11zhp";

                /// <summary>
                /// Draw 4 cards.<br/>
                /// 0-Cost Spell
                /// </summary>
                public const string SoldiersOfTheColdDark = "FB_LK001";

                /// <summary>
                /// Deal damage to the enemy hero. +1 Damage each time.<br/>
                /// 0-Cost HeroPower
                /// </summary>
                public const string RemorselessWinterTavernBrawl = "FB_LK005";

                /// <summary>
                /// Summon a different Frozen Throne boss. <i> You aren't worth the Lich King's time.</i><br/>
                /// 0-Cost Spell
                /// </summary>
                public const string ToMyAidUnderling = "FB_LK006";

                /// <summary>
                /// (No Text)<br/>
                /// 0-Cost Hero
                /// </summary>
                public const string SaiShadestorm = "PVPDR_Hero_Sai";

                /// <summary>
                /// (No Text)<br/>
                /// 0-Cost Hero
                /// </summary>
                public const string ScarletLeafdancer = "PVPDR_Hero_Scarlet";

                /// <summary>
                /// <b>Rush</b> <i>Doesn't leave a <b>Corpse</b>.</i><br/>
                /// 2-Cost 2/2 Undead Minion
                /// </summary>
                public const string RisenGhoul = "PVPDR_RLK_Passive03m1";

                /// <summary>
                /// <i>Doesn't leave a <b>Corpse</b>.</i><br/>
                /// 1-Cost 1/1 Undead Minion
                /// </summary>
                public const string RisenGroom = "PVPDR_RLK_Passive04m1";

                /// <summary>
                /// Summon a 2/1 Ghoul with <b>Charge</b>. It dies at end of turn.<br/>
                /// 2-Cost HeroPower
                /// </summary>
                public const string GhoulBlitz = "PVPDR_RLK_Sai_HP1";

                /// <summary>
                /// <b>Charge</b> At the end of your turn, this minion dies.<br/>
                /// 1-Cost 2/1 Undead Minion
                /// </summary>
                public const string RelentlessGhoul = "PVPDR_RLK_Sai_HP1t";

                /// <summary>
                /// Gain a <b>Corpse</b>. Draw a card.<br/>
                /// 2-Cost HeroPower
                /// </summary>
                public const string GatheringStorm = "PVPDR_RLK_Sai_HP2";

                /// <summary>
                /// Give a friendly minion +3/+3. It dies at the end of your turn.<br/>
                /// 2-Cost HeroPower
                /// </summary>
                public const string LichborneMight1 = "PVPDR_RLK_Sai_HP3";

                /// <summary>
                /// This minion has +3/+3, but will die a horrible death at the end of the turn.<br/>
                /// Enchantment
                /// </summary>
                public const string LichborneMight2 = "PVPDR_RLK_Sai_HP3e";

                /// <summary>
                /// Summon a 2/1 Bloodworm with <b>Lifesteal</b>.<br/>
                /// 2-Cost HeroPower
                /// </summary>
                public const string BloodParasite = "PVPDR_RLK_Scarlet_HP1";

                /// <summary>
                /// <b>Lifesteal</b><br/>
                /// 1-Cost 2/1 Beast Minion
                /// </summary>
                public const string Bloodworm = "PVPDR_RLK_Scarlet_HP1t";

                /// <summary>
                /// Spend up to 3 <b>Corpses</b>. For each, reduce the cost of a card in your hand by (1).<br/>
                /// 1-Cost HeroPower
                /// </summary>
                public const string Hematology1 = "PVPDR_RLK_Scarlet_HP2";

                /// <summary>
                /// Reduced Cost.<br/>
                /// Enchantment
                /// </summary>
                public const string Hematology2 = "PVPDR_RLK_Scarlet_HP2e1";

                /// <summary>
                /// <b>Discover</b> an Undead.<br/>
                /// 2-Cost HeroPower
                /// </summary>
                public const string Scourging = "PVPDR_RLK_Scarlet_HP3";

                /// <summary>
                /// <b>Battlecry:</b> Give your other Undead +2/+1 and <b>Reborn</b>.<br/>
                /// 5-Cost 4/2 Undead/Beast Minion
                /// </summary>
                public const string GluthTavernBrawl2 = "PVPDR_Sai_T1";

                /// <summary>
                /// +2/+1<br/>
                /// Enchantment
                /// </summary>
                public const string GluthsGrowth = "PVPDR_Sai_T1e";

                /// <summary>
                /// <b>Deathrattle:</b> Equip a 2/3 Wings of Glaciaxe.<br/>
                /// 4-Cost Weapon
                /// </summary>
                public const string Glaciaxe = "PVPDR_Sai_T2";

                /// <summary>
                /// <b>Windfury</b> <b>Deathrattle:</b> Summon three 1/1 Zombies with <b>Reborn</b>.<br/>
                /// 4-Cost Weapon
                /// </summary>
                public const string WingsOfGlaciaxe = "PVPDR_Sai_T2a";

                /// <summary>
                /// (No Text)<br/>
                /// 1-Cost 1/1 Undead Minion
                /// </summary>
                public const string Ghoul = "PVPDR_Sai_T2at";

                /// <summary>
                /// <b>Reborn</b><br/>
                /// 1-Cost 1/1 Undead Minion
                /// </summary>
                public const string ShamblingZombie = "PVPDR_Sai_T2at1";

                /// <summary>
                /// Resurrect the minions your Frost spells have killed this game.<br/>
                /// 6-Cost Spell
                /// </summary>
                public const string RemembranceOfIce = "PVPDR_Sai_T3";

                /// <summary>
                /// Spend up to 10 <b>Corpses</b> and add an Unholy Rune card to your hand for each.<br/>
                /// 4-Cost Spell
                /// </summary>
                public const string UnholyEmbrace = "PVPDR_Sai_T4";

                /// <summary>
                /// <b>Battlecry:</b> Summon two Undead from your deck and <b>Freeze</b> them.<br/>
                /// 7-Cost 6/4 Undead/Beast Minion
                /// </summary>
                public const string GluthSicle = "PVPDR_Sai_T5";

                /// <summary>
                /// <b>Rush</b> <b>Revive</b>: (2)<br/>
                /// 5-Cost 5/5 Undead Minion
                /// </summary>
                public const string InexorableGhoul = "PVPDR_Sai_T6";

                /// <summary>
                /// <b>Deathrattle:</b> Spread to a neighbor, then deal 5 damage to your hero.<br/>
                /// Enchantment
                /// </summary>
                public const string FesteringWound = "PVPDR_Sai_T6e";

                /// <summary>
                /// After your hero takes damage, deal 1 damage to all enemies and lose 1 Durability.<br/>
                /// 3-Cost Weapon
                /// </summary>
                public const string RunedSoulblade = "PVPDR_Scarlet_T1";

                /// <summary>
                /// Whenever your hero takes damage, deal 1 damage to all enemies and lose 1 Durability.<br/>
                /// Enchantment
                /// </summary>
                public const string DangerousRunes = "PVPDR_Scarlet_T1e";

                /// <summary>
                /// Gain 1<b> Corpse</b>, destroy 1 enemy |4(minion, minions), and draw 1 |4(card, cards). <i>(Improves during run.)</i><br/>
                /// 3-Cost Spell
                /// </summary>
                public const string ScourgeStrike = "PVPDR_Scarlet_T2";

                /// <summary>
                /// Whenever your hero is healed, this minion gains that much Attack and Health.<br/>
                /// 1-Cost 2/2 Undead/Beast Minion
                /// </summary>
                public const string Crimson = "PVPDR_Scarlet_T3";

                /// <summary>
                /// <b>Battlecry:</b> For the rest of the game, whenever you consume one or more <b>Corpses</b>, restore 2 Health to your hero.<br/>
                /// 3-Cost Weapon
                /// </summary>
                public const string IronweaveBloodletter = "PVPDR_Scarlet_T4";

                /// <summary>
                /// Whenever you play a minion, give it <b>Reborn</b> and this loses 1 Durability.<br/>
                /// 3-Cost Weapon
                /// </summary>
                public const string GreatswordOfTheEbonBlade = "PVPDR_Scarlet_T5";

                /// <summary>
                /// Infect a minion with "<b>Deathrattle:</b> Deal 3 damage to your hero, then infect a neighbor."<br/>
                /// 2-Cost Spell
                /// </summary>
                public const string ContagionConcoction = "PVPDR_Scarlet_T6";

                /// <summary>
                /// <b>Deathrattle:</b> Infect a neighbor, then deal 3 damage to your hero.<br/>
                /// Enchantment
                /// </summary>
                public const string FesteringContagion = "PVPDR_Scarlet_T6e";

                /// <summary>
                /// <b>Charge</b><br/>
                /// 2-Cost 2/1 Undead/Beast Minion
                /// </summary>
                public const string BlightBoarTavernBrawl = "TB_BotB_BlightBoar";

                /// <summary>
                /// <i>The lead guitarist of Blight Boar has joined his bandmates to play at the festival instead of their usual Darkmoon Island set.</i><br/>
                /// 0-Cost Hero
                /// </summary>
                public const string CageHeadTavernBrawl = "TB_BotB_CageHead";

                /// <summary>
                /// Summon a 2/1 Blight Boar with <b>Charge</b>. It dies at end of turn.<br/>
                /// 2-Cost HeroPower
                /// </summary>
                public const string BlightChargeTavernBrawl = "TB_BotB_CageHead_001p";

                /// <summary>
                /// (No Text)<br/>
                /// 0-Cost Hero
                /// </summary>
                public const string MetalStarTavernBrawl = "TB_BotB_RisingStar_DK";

                /// <summary>
                /// (No Text)<br/>
                /// 0-Cost Hero
                /// </summary>
                public const string DeathKnightArthasTavernBrawl = "TB_HunterPrince_ArthasH";

                /// <summary>
                /// (No Text)<br/>
                /// 0-Cost Hero
                /// </summary>
                public const string TheLichKingTavernBrawl = "THD_001";

                /// <summary>
                /// Summon a 1/1 Zombie with <b>Reborn</b> and <b>Charge</b>. It dies at end of turn.<br/>
                /// 2-Cost HeroPower
                /// </summary>
                public const string RelentlessGhoulHeroic1 = "THD_001hp";

                /// <summary>
                /// After you spend a <b>Corpse</b> summon a Risen Skeleton with stats equal to <b>Corpses</b> spent.<br/>
                /// 0-Cost Spell
                /// </summary>
                public const string TheLichKing_CadaverCollector = "THD_001p";

                /// <summary>
                /// <i>Doesn't leave a <b>Corpse</b>.</i><br/>
                /// 1-Cost 1/1 Undead Minion
                /// </summary>
                public const string TheLichKing_RisenSkeleton = "THD_001pt";

                /// <summary>
                /// (No Text)<br/>
                /// 0-Cost Hero
                /// </summary>
                public const string TheHeadlessHorseman = "THD_002";

                /// <summary>
                /// Give your minions "<b>Deathrattle:</b> Summon a 2/1 Squashling with <b>Rush</b>."<br/>
                /// 2-Cost HeroPower
                /// </summary>
                public const string SquashlingTrickHeroic = "THD_002hp";

                /// <summary>
                /// <b>Rush</b><br/>
                /// 2-Cost 2/1 Minion
                /// </summary>
                public const string SquashlingHeroic = "THD_002hpt";

                /// <summary>
                /// <b>Passive.</b> Your first minion each turn has <b>Echo</b>.<br/>
                /// 0-Cost Spell
                /// </summary>
                public const string TheHeadlessHorseman_UnholyTreat3 = "THD_002p";

                /// <summary>
                /// (No Text)<br/>
                /// 0-Cost Hero
                /// </summary>
                public const string PitBossReska = "THD_003";

                /// <summary>
                /// Summon a 1/1 Ghoul with <b>Charge</b> and <b>Reborn</b>. It dies at end of turn.<br/>
                /// 2-Cost HeroPower
                /// </summary>
                public const string RelentlessGhoulHeroic2 = "THD_003hp";

                /// <summary>
                /// <b>Charge</b>, <b>Reborn</b> At the end of your turn, this minion dies.<br/>
                /// 1-Cost 1/1 Undead Minion
                /// </summary>
                public const string RelentlessGhoulHeroic3 = "THD_003hpt";

                /// <summary>
                /// <b>Passive</b> After 5 friendly Undead die, <b>Excavate</b>.<br/>
                /// 0-Cost Spell
                /// </summary>
                public const string PitBossReska_EndlessExcavation = "THD_003p";

                /// <summary>
                /// (No Text)<br/>
                /// 0-Cost Hero
                /// </summary>
                public const string Arfus = "THD_100";

                /// <summary>
                /// Spend up to 3 <b>Corpses</b>. For each, reduce the cost of a card in your hand by (1).<br/>
                /// 1-Cost HeroPower
                /// </summary>
                public const string GiveADogABoneHeroic2 = "THD_100hp";

                /// <summary>
                /// After you play an Unholy Rune card, <b>Excavate</b>. Swap to Blood. <i><b>Legendary</b> treasures are random.</i><br/>
                /// 0-Cost Spell
                /// </summary>
                public const string Arfus_DigUpUnholy = "THD_100p";

                /// <summary>
                /// After you play a Frost Rune card, <b>Excavate</b>. Swap to Unholy. <i><b>Legendary</b> treasures are random.</i><br/>
                /// 0-Cost Spell
                /// </summary>
                public const string Arfus_DigUpFrost = "THD_100p2";

                /// <summary>
                /// After you play a Blood Rune card, <b>Excavate</b>. Swap to Frost. <i><b>Legendary</b> treasures are random.</i><br/>
                /// 0-Cost Spell
                /// </summary>
                public const string Arfus_DigUpBlood = "THD_100p3";

                /// <summary>
                /// Your next spell this turn has <b>Spell Damage +2</b>.<br/>
                /// 1-Cost HeroPower
                /// </summary>
                public const string ColdBloodedHeroic1 = "TWI_001hp";

                /// <summary>
                /// You have <b>Spell Damage +1</b> for your next spell this turn.<br/>
                /// Enchantment
                /// </summary>
                public const string ColdBloodedHeroic2 = "TWI_001hpe";

                /// <summary>
                /// <b>Deathrattle:</b> Summon every minion killed by this weapon.<br/>
                /// 7-Cost Weapon
                /// </summary>
                public const string TheLichKing_FrostmourneToken = "ICC_314t1";

                /// <summary>
                /// Remove the top 5 cards of your deck. Summon any minions removed.<br/>
                /// 6-Cost Spell
                /// </summary>
                public const string TheLichKing_ArmyOfTheFrozenThroneToken = "ICC_314t2";

                /// <summary>
                /// Destroy all minions. Remove the top card from your deck for each minion destroyed.<br/>
                /// 5-Cost Spell
                /// </summary>
                public const string TheLichKing_DoomPactToken = "ICC_314t3";

                /// <summary>
                /// Steal a minion from your opponent's deck and add it to your hand.<br/>
                /// 2-Cost Spell
                /// </summary>
                public const string TheLichKing_DeathGripToken = "ICC_314t4";

                /// <summary>
                /// Deal $5 damage to an enemy, or restore #5 Health to a friendly character.<br/>
                /// 2-Cost Spell
                /// </summary>
                public const string TheLichKing_DeathCoilToken = "ICC_314t5";

                /// <summary>
                /// Destroy a minion. Your hero takes damage equal to its Health.<br/>
                /// 2-Cost Spell
                /// </summary>
                public const string TheLichKing_ObliterateToken = "ICC_314t6";

                /// <summary>
                /// Give your minions +2/+2 and <b>Elusive</b>.<br/>
                /// 4-Cost Spell
                /// </summary>
                public const string TheLichKing_AntiMagicShellToken2 = "ICC_314t7";

                /// <summary>
                /// Deal $3 damage to all enemies.<br/>
                /// 3-Cost Spell
                /// </summary>
                public const string TheLichKing_DeathAndDecayToken = "ICC_314t8";

                /// <summary>
                /// The next spell you cast this turn costs (0).<br/>
                /// 1-Cost Spell
                /// </summary>
                public const string BloodTapICECROWN = "ICCA01_003";

                /// <summary>
                /// Summon seven 3/3 Ghouls with <b>Taunt</b>.<br/>
                /// 10-Cost Spell
                /// </summary>
                public const string ArmyOfTheDeadICECROWN = "ICCA01_004";

                /// <summary>
                /// (No Text)<br/>
                /// 2-Cost Weapon
                /// </summary>
                public const string FrostmourneICECROWN1 = "ICCA01_005";

                /// <summary>
                /// <b>Battlecry:</b> Remove all your minions. <b>Deathrattle:</b> Resummon them.<br/>
                /// 7-Cost Weapon
                /// </summary>
                public const string FrostmourneICECROWN2 = "ICCA08_020";

                /// <summary>
                /// Set the enemy hero's remaining Health to 1.<br/>
                /// 1-Cost Spell
                /// </summary>
                public const string TheTrueLich = "ICCA08_021";

                /// <summary>
                /// Whenever an enemy dies this game, take control of it.<br/>
                /// 1-Cost Spell
                /// </summary>
                public const string FallenChampions = "ICCA08_022";

                /// <summary>
                /// Set minions in your opponent's hand and deck to 1/1.<br/>
                /// 1-Cost Spell
                /// </summary>
                public const string NecroticPlague = "ICCA08_023";

                /// <summary>
                /// 1/1.<br/>
                /// Enchantment
                /// </summary>
                public const string NecroticPlague_PlaguedEnchantment = "ICCA08_023e";

                /// <summary>
                /// Deal $2 damage to your opponent for each minion in their deck.<br/>
                /// 1-Cost Spell
                /// </summary>
                public const string TheHunted = "ICCA08_024";

                /// <summary>
                /// Destroy all enemy minions that cost (3) or less, wherever they are.<br/>
                /// 1-Cost Spell
                /// </summary>
                public const string PurgeTheWeak = "ICCA08_025";

                /// <summary>
                /// Deal $2 damage for each duplicate in opponent’s deck.<br/>
                /// 1-Cost Spell
                /// </summary>
                public const string SoulReaper = "ICCA08_026";

                /// <summary>
                /// Gain 100 Armor.<br/>
                /// 1-Cost Spell
                /// </summary>
                public const string TheTrueKing = "ICCA08_027";

                /// <summary>
                /// Destroy every spell in your opponent's hand and deck.<br/>
                /// 1-Cost Spell
                /// </summary>
                public const string ThePriceOfPower = "ICCA08_028";

                /// <summary>
                /// Your opponent can't emote.<br/>
                /// 1-Cost Spell
                /// </summary>
                public const string ShutUpPriest = "ICCA08_029";

                /// <summary>
                /// Deal 1 damage to the enemy hero. +1 Damage each time.<br/>
                /// 0-Cost HeroPower
                /// </summary>
                public const string RemorselessWinterICECROWN = "ICCA08_030p";

                /// <summary>
                /// <b>Battlecry:</b> Remove all your minions. <b>Deathrattle:</b> Resummon them.<br/>
                /// 6-Cost Weapon
                /// </summary>
                public const string FrostmourneICECROWN3 = "Story_10_Frostmourne";

                /// <summary>
                /// Increased Health<br/>
                /// Enchantment
                /// </summary>
                public const string HealthEnchantment = "LOOTA_Health";

                /// <summary>
                /// <i>The undead nerubians were quick to attack the Horde... and their peons.</i><br/>
                /// 0-Cost Hero
                /// </summary>
                public const string UnderqueenZarzhet = "Story_03_Zarzhet";

                /// <summary>
                /// Deal $2 damage to a random enemy minion. If it dies, summon a Ghoul.<br/>
                /// 2-Cost HeroPower
                /// </summary>
                public const string DarkConversion = "Story_03_ZarzhetHP";

                /// <summary>
                /// <i>The time has come to face the inevitable.</i><br/>
                /// 0-Cost Hero
                /// </summary>
                public const string PrinceArthas1 = "Story_04_Arthas";

                /// <summary>
                /// Summon three 2/2 Ghouls.<br/>
                /// 0-Cost HeroPower
                /// </summary>
                public const string ScourgeArmy = "Story_04_ArthasHP";

                /// <summary>
                /// <b>Deathrattle:</b> Summon every minion killed by this weapon.<br/>
                /// 7-Cost Weapon
                /// </summary>
                public const string FrostmourneDARKMOON_FAIRE = "Story_04_Frostmourne";

                /// <summary>
                /// At the end of your turn, transform a non-<b>Legendary</b> enemy minion into a 1/1 Skeleton. Take control of it.<br/>
                /// 0-Cost HeroPower
                /// </summary>
                public const string Infection1 = "Story_04_IcebladeHP";

                /// <summary>
                /// <b>Battlecry and Deathrattle:</b> Deal 2 damage to all enemy minions.<br/>
                /// 4-Cost Weapon
                /// </summary>
                public const string Iceblade = "Story_04_IcebladeWeapon";

                /// <summary>
                /// This minion will transform into a Skeleton in 1 turns.<br/>
                /// Enchantment
                /// </summary>
                public const string Infection2 = "Story_04_Infectione";

                /// <summary>
                /// <i>War has taken its toll on the people of Azeroth. Perhaps you could use this to your advantage...</i><br/>
                /// 0-Cost Hero
                /// </summary>
                public const string FallenSoldierHeroic = "Story_09_Teron_007hb";

                /// <summary>
                /// (No Text)<br/>
                /// 0-Cost Hero
                /// </summary>
                public const string TeronGorefiendHeroicTHE_BARRENS = "Story_09_Teron_007hb2";

                /// <summary>
                /// <b>Passive</b> Convert fatal damage to minions into Health for this soldier.<br/>
                /// 0-Cost HeroPower
                /// </summary>
                public const string DarkInfusion = "Story_09_Teron_007p";

                /// <summary>
                /// <i>To prove your brother wrong, you must clear the forests of any foes, no matter how dangerous…</i><br/>
                /// 0-Cost Hero
                /// </summary>
                public const string PrinceArthasHeroic = "Story_10_Arthas_001hb";

                /// <summary>
                /// Equip Frostmourne.<br/>
                /// 6-Cost HeroPower
                /// </summary>
                public const string EquipFrostmourne = "Story_10_Arthas_001p";

                /// <summary>
                /// <i>If Arthas reaches the Lich King in the Frozen Throne, all is lost. This is your final chance to stop him.</i><br/>
                /// 0-Cost Hero
                /// </summary>
                public const string DeathKnightArthasHeroic = "Story_10_Arthas_007hb";

                /// <summary>
                /// <b>Passive</b> If you have more minions than your opponent, draw a card at the start of your turn.<br/>
                /// 0-Cost HeroPower
                /// </summary>
                public const string DarkDetermination = "Story_10_Arthas_007p";

                /// <summary>
                /// (No Text)<br/>
                /// 0-Cost Hero
                /// </summary>
                public const string DeathKnightVelasHeroic = "Story_10_Velas_004hb";

                /// <summary>
                /// Summon a random undead.<br/>
                /// 0-Cost HeroPower
                /// </summary>
                public const string GraveCall = "Story_10_Velas_004p";

                /// <summary>
                /// Deal your weapon's damage to all enemy minions. Draw 3 cards.<br/>
                /// 8-Cost Spell
                /// </summary>
                public const string FatesDemand = "Story_10_FatesDemand";

                /// <summary>
                /// Put a random minion from each player's hand into the battlefield. If yours costs more, attack the enemy hero.<br/>
                /// 4-Cost Spell
                /// </summary>
                public const string Manipulate = "Story_10_Manipulate";

                /// <summary>
                /// <b>Poisonous</b><br/>
                /// Enchantment
                /// </summary>
                public const string PoisonBreath_DeathlyPoisonCoreEnchantment = "CORE_EDR_002e";

                /// <summary>
                /// <b>Rush</b> <i>Doesn't leave a <b>Corpse</b>.</i><br/>
                /// 2-Cost 2/2 Undead Minion
                /// </summary>
                public const string RisenGhoulCoreToken1 = "RLK_008t";

                /// <summary>
                /// <b>Casts When Drawn</b> Summon a 2/2 Undead Peasant.<br/>
                /// 1-Cost Spell
                /// </summary>
                public const string PlaguedGrain_GrainCrateCoreToken = "RLK_039t";

                /// <summary>
                /// +1/+1 and <b>Elusive</b>.<br/>
                /// Enchantment
                /// </summary>
                public const string AntiMagicShell_AntiMagicShellCoreEnchantment1 = "RLK_048e";

                /// <summary>
                /// <b>Taunt</b> <i>Doesn't leave a <b>Corpse</b>.</i><br/>
                /// 1-Cost 1/3 Undead Minion
                /// </summary>
                public const string BattlefieldNecromancer_RisenFootmanCoreToken1 = "RLK_061t";

                /// <summary>
                /// <b>Rush</b> <b>Reborn</b><br/>
                /// 1-Cost 1/1 Minion
                /// </summary>
                public const string Possessifier_PossessedFighterCoreToken = "RLK_077t";

                /// <summary>
                /// <b>Rush</b> <i>Doesn't leave a <b>Corpse</b>.</i><br/>
                /// 1-Cost 1/1 Undead Minion
                /// </summary>
                public const string LordMarrowgar_RisenGolemCoreToken = "RLK_085t";

                /// <summary>
                /// <b>Taunt</b> <i>Doesn't leave a <b>Corpse</b>.</i><br/>
                /// 3-Cost 3/3 Undead Minion
                /// </summary>
                public const string YmirjarDeathbringer_RisenYmirjarCoreToken1 = "RLK_226t";

                /// <summary>
                /// <b>Reborn</b><br/>
                /// 1-Cost 1/1 Undead Minion
                /// </summary>
                public const string GraveyardShift_ShamblingZombieCoreToken1 = "RLK_705t";

                /// <summary>
                /// <b>Deathrattle:</b> Deal 2 damage to a random enemy.<br/>
                /// 2-Cost 2/1 Elemental Minion
                /// </summary>
                public const string RimeElementalCoreToken1 = "RLK_907t";

                /// <summary>
                /// <b>Battlecry</b>: Gain a <b>Corpse</b>.<br/>
                /// 1-Cost 1/3 Undead Minion
                /// </summary>
                public const string BodyBaggerCore = "RLK_Prologue_503";

                /// <summary>
                /// <b>Rush</b> <i>Doesn't leave a <b>Corpse</b>.</i><br/>
                /// 2-Cost 2/2 Undead Minion
                /// </summary>
                public const string RisenGhoulCoreToken2 = "RLK_Prologue_RLK_008t";

                /// <summary>
                /// <b>Lifesteal</b> Deal $6 damage to a minion.<br/>
                /// 4-Cost Spell
                /// </summary>
                public const string DeathStrikeCore = "RLK_Prologue_RLK_024";

                /// <summary>
                /// <b>Lifesteal</b> Deal $6 damage to a minion.<br/>
                /// 4-Cost Spell
                /// </summary>
                public const string DeathStrike_DeathStrikeCore = "RLK_Prologue_RLK_024_AI";

                /// <summary>
                /// Deal $3 damage to a minion. If that kills it, gain a <b>Corpse</b>.<br/>
                /// 1-Cost Spell
                /// </summary>
                public const string HeartStrikeCore = "RLK_Prologue_RLK_034";

                /// <summary>
                /// Give your minions +1/+1 and <b>Elusive</b>.<br/>
                /// 3-Cost Spell
                /// </summary>
                public const string AntiMagicShellCore = "RLK_Prologue_RLK_048";

                /// <summary>
                /// +1/+1 and <b>Elusive</b>.<br/>
                /// Enchantment
                /// </summary>
                public const string AntiMagicShell_AntiMagicShellCoreEnchantment2 = "RLK_Prologue_RLK_048e";

                /// <summary>
                /// Raise up to 5 <b>Corpses</b> as 2/2 Risen Ghouls with <b>Rush</b>.<br/>
                /// 5-Cost Spell
                /// </summary>
                public const string ArmyOfTheDeadCore = "RLK_Prologue_RLK_060";

                /// <summary>
                /// At the end of your turn, raise a <b>Corpse</b> as a 1/2 Risen Footman with <b>Taunt</b>.<br/>
                /// 2-Cost 2/3 Minion
                /// </summary>
                public const string BattlefieldNecromancerCore = "RLK_Prologue_RLK_061";

                /// <summary>
                /// <b>Taunt</b> <i>Doesn't leave a <b>Corpse</b>.</i><br/>
                /// 1-Cost 1/2 Undead Minion
                /// </summary>
                public const string BattlefieldNecromancer_RisenFootmanCoreToken2 = "RLK_Prologue_RLK_061t";

                /// <summary>
                /// <b>Battlecry:</b> Destroy a random minion in your opponent's hand, deck, and battlefield.<br/>
                /// 7-Cost 4/6 Undead Minion
                /// </summary>
                public const string PatchwerkCore = "RLK_Prologue_RLK_071";

                /// <summary>
                /// <b>Battlecry</b>: Deal 2 damage to an enemy and your hero.<br/>
                /// 1-Cost 1/2 Undead Minion
                /// </summary>
                public const string NoxiousCadaverCore = "RLK_Prologue_RLK_079";

                /// <summary>
                /// <b>Taunt</b> <b>Deathrattle:</b> Return this to your hand. It costs Health instead of Mana.<br/>
                /// 5-Cost 3/5 Undead Minion
                /// </summary>
                public const string DeathbringerSaurfangCore = "RLK_Prologue_RLK_082";

                /// <summary>
                /// Draw a card. Spend 2 <b>Corpses</b> to draw another.<br/>
                /// 2-Cost Spell
                /// </summary>
                public const string DefrostCore = "RLK_Prologue_RLK_101";

                /// <summary>
                /// Enemy characters can't be healed.<br/>
                /// 4-Cost 3/6 Undead Minion
                /// </summary>
                public const string RepulsiveGargantuanCore = "RLK_Prologue_RLK_115";

                /// <summary>
                /// Destroy a minion. Your hero takes damage equal to its Health.<br/>
                /// 2-Cost Spell
                /// </summary>
                public const string ObliterateCore = "RLK_Prologue_RLK_125";

                /// <summary>
                /// Destroy a minion. Your hero takes damage equal to its Health.<br/>
                /// 2-Cost Spell
                /// </summary>
                public const string Obliterate_ObliterateCore = "RLK_Prologue_RLK_125_AI";

                /// <summary>
                /// <b>Reborn</b> <b>Battlecry and Deathrattle:</b> Deal 2 damage to a random enemy.<br/>
                /// 4-Cost 3/3 Undead Minion
                /// </summary>
                public const string ThassarianCore = "RLK_Prologue_RLK_223";

                /// <summary>
                /// <b>Battlecry:</b> Draw 2 spells. If they're both Frost spells, deal 2 damage to all enemies.<br/>
                /// 6-Cost 5/6 Minion
                /// </summary>
                public const string OverseerFrigidaraCore = "RLK_Prologue_RLK_224";

                /// <summary>
                /// <b>Taunt</b>. <b>Deathrattle:</b> Spend 3 <b>Corpses</b> to summon a 3/3 Risen Ymirjar with <b>Taunt</b>.<br/>
                /// 3-Cost 3/3 Undead Minion
                /// </summary>
                public const string YmirjarDeathbringerCore = "RLK_Prologue_RLK_226";

                /// <summary>
                /// <b>Taunt</b> <i>Doesn't leave a <b>Corpse</b>.</i><br/>
                /// 3-Cost 3/3 Undead Minion
                /// </summary>
                public const string YmirjarDeathbringer_RisenYmirjarCoreToken2 = "RLK_Prologue_RLK_226t";

                /// <summary>
                /// <b>Deathrattle:</b> Draw a Frost spell.<br/>
                /// 2-Cost 2/2 Undead Minion
                /// </summary>
                public const string HarbingerOfWinterCore = "RLK_Prologue_RLK_511";

                /// <summary>
                /// Summon two 1/1 Zombies with <b>Reborn</b>.<br/>
                /// 3-Cost Spell
                /// </summary>
                public const string GraveyardShiftCore = "RLK_Prologue_RLK_705";

                /// <summary>
                /// <b>Reborn</b><br/>
                /// 1-Cost 1/1 Undead Minion
                /// </summary>
                public const string GraveyardShift_ShamblingZombieCoreToken2 = "RLK_Prologue_RLK_705t";

                /// <summary>
                /// Give your minions +1 Attack. Spend 5 <b>Corpses</b> to give them +3 instead.<br/>
                /// 4-Cost Spell
                /// </summary>
                public const string GraveStrengthCore = "RLK_Prologue_RLK_707";

                /// <summary>
                /// <b>Battlecry and Deathrattle:</b> Draw a card.<br/>
                /// 3-Cost 2/2 Undead/Draenei Minion
                /// </summary>
                public const string ChillfallenBaronCore = "RLK_Prologue_RLK_708";

                /// <summary>
                /// Deal $2 damage to all enemies. Draw a card.<br/>
                /// 4-Cost Spell
                /// </summary>
                public const string RemorselessWinterCore = "RLK_Prologue_RLK_709";

                /// <summary>
                /// <b>Taunt</b>, <b>Lifesteal</b> At the end of your turn, attack the lowest Health enemy.<br/>
                /// 6-Cost 5/6 Undead Minion
                /// </summary>
                public const string GnomeMuncherCore = "RLK_Prologue_RLK_720";

                /// <summary>
                /// Costs (1) less for each <b>Corpse</b> you've spent this game.<br/>
                /// 10-Cost 8/8 Undead Minion
                /// </summary>
                public const string StitchedGiantCore = "RLK_Prologue_RLK_744";

                /// <summary>
                /// <b>Battlecry:</b> Summon two 2/1 Rime Elementals with "<b>Deathrattle:</b> Deal 2 damage to a random enemy."<br/>
                /// 5-Cost 3/3 Undead Minion
                /// </summary>
                public const string RimeSculptorCore = "RLK_Prologue_RLK_752";

                /// <summary>
                /// <b>Battlecry:</b> Spend a <b>Corpse</b> to gain +1/+2.<br/>
                /// 2-Cost 2/2 Undead Minion
                /// </summary>
                public const string BonediggerGeistCore = "RLK_Prologue_RLK_753";

                /// <summary>
                /// <b>Deathrattle:</b> Deal 2 damage to a random enemy.<br/>
                /// 2-Cost 2/1 Elemental Minion
                /// </summary>
                public const string RimeElementalCoreToken2 = "RLK_Prologue_RLK_907t";

                /// <summary>
                /// <b>Rush</b><br/>
                /// 5-Cost 5/5 Undead Minion
                /// </summary>
                public const string ConstructQuarter_ShamblingHorrorToken = "NX2_036t";

                /// <summary>
                /// <b>Rush</b> <b>Freeze</b> any character damaged by this minion.<br/>
                /// 1-Cost 2/1 Dragon/Undead Minion
                /// </summary>
                public const string FrostQueenSindragosa_SindragosasWingToken1 = "NX2_037t";

                /// <summary>
                /// <b>Rush</b> <b>Freeze</b> any character damaged by this minion.<br/>
                /// 1-Cost 2/1 Dragon/Undead Minion
                /// </summary>
                public const string FrostQueenSindragosa_SindragosasWingToken2 = "NX2_037t2";

                /// <summary>
                /// {0}<br/>
                /// Enchantment
                /// </summary>
                public const string IcyRemembrance = "PVPDR_Sai_T3e1";

                /// <summary>
                /// The next spell you cast this turn costs (2) less.<br/>
                /// Enchantment
                /// </summary>
                public const string FrostStrike_GlacialAdvanceEnchantment1 = "RLK_025e";

                /// <summary>
                /// The next spell you cast this turn costs (2) less.<br/>
                /// Enchantment
                /// </summary>
                public const string FrostStrike_GlacialAdvanceEnchantment2 = "RLK_025o";

                /// <summary>
                /// Increased Health.<br/>
                /// Enchantment
                /// </summary>
                public const string VampiricBlood_VampiricStrengthEnchantment = "RLK_051e";

                /// <summary>
                /// Increased Health.<br/>
                /// Enchantment
                /// </summary>
                public const string Hematurge_WintersGiftEnchantment = "RLK_066e";

                /// <summary>
                /// +2/+2.<br/>
                /// Enchantment
                /// </summary>
                public const string LordMarrowgar_BonestormEnchantment = "RLK_085e";

                /// <summary>
                /// <b>Deathrattle:</b> Summon a 2/2 Zombie with <b>Taunt</b> for your opponent.<br/>
                /// Enchantment
                /// </summary>
                public const string Blightfang_PlaguedEnchantment = "RLK_225e";

                /// <summary>
                /// For the rest of the game, deal 3 damage to your opponent at the end of your turns.<br/>
                /// Enchantment
                /// </summary>
                public const string AlexandrosMograine_MograinesMigraineEnchantment = "RLK_706e3";

                /// <summary>
                /// +1 Attack.<br/>
                /// Enchantment
                /// </summary>
                public const string GraveStrength_GraveMarkEnchantmentRETURN_OF_THE_LICH_KING1 = "RLK_707e";

                /// <summary>
                /// +3 Attack.<br/>
                /// Enchantment
                /// </summary>
                public const string GraveStrength_GraveForceEnchantment1 = "RLK_707e2";

                /// <summary>
                /// Costs (1) less.<br/>
                /// Enchantment
                /// </summary>
                public const string Runeforging_RuneforgedEnchantment = "RLK_715e";

                /// <summary>
                /// +1/+2.<br/>
                /// Enchantment
                /// </summary>
                public const string BonediggerGeist_DugUpEnchantment1 = "RLK_753e";

                /// <summary>
                /// +2 Attack.<br/>
                /// Enchantment
                /// </summary>
                public const string SkeletalSidekick_ThrownABoneEnchantmentRETURN_OF_THE_LICH_KING = "RLK_958e";

                /// <summary>
                /// Deal $3 damage to a minion. If that kills it, <b>Discover</b> a Frost Rune card.<br/>
                /// 2-Cost Spell
                /// </summary>
                public const string FrostStrike = "RLK_Prologue_025";

                /// <summary>
                /// Choose an enemy minion. Your minions attack it. Resummon any that die.<br/>
                /// 3-Cost Spell
                /// </summary>
                public const string UnholyFrenzy = "RLK_Prologue_056";

                /// <summary>
                /// <b>Battlecry:</b> Spend a <b>Corpse</b> to <b>Discover</b> a Blood Rune card.<br/>
                /// 2-Cost 2/3 Minion
                /// </summary>
                public const string Hematurge = "RLK_Prologue_066";

                /// <summary>
                /// (No Text)<br/>
                /// 0-Cost Hero
                /// </summary>
                public const string ArthasHeroic1 = "RLK_Prologue_Arthas_002hp";

                /// <summary>
                /// <b>Hero Power</b> Summon a 1/1 Ghoul with <b>Charge</b>. It dies at end of turn.<br/>
                /// 2-Cost HeroPower
                /// </summary>
                public const string GhoulChargeRETURN_OF_THE_LICH_KING1 = "RLK_Prologue_Arthas_002p";

                /// <summary>
                /// (No Text)<br/>
                /// 0-Cost Hero
                /// </summary>
                public const string ArthasHeroic2 = "RLK_Prologue_Arthas_003hp";

                /// <summary>
                /// <b>Hero Power</b> Summon a 1/1 Ghoul with <b>Charge</b>. It dies at end of turn.<br/>
                /// 2-Cost HeroPower
                /// </summary>
                public const string GhoulChargeRETURN_OF_THE_LICH_KING2 = "RLK_Prologue_Arthas_003p";

                /// <summary>
                /// (No Text)<br/>
                /// 0-Cost Hero
                /// </summary>
                public const string ArthasHeroic3 = "RLK_Prologue_Arthas_004hp";

                /// <summary>
                /// <b>Hero Power</b> Summon a 1/1 Ghoul with <b>Charge</b>. It dies at end of turn.<br/>
                /// 2-Cost HeroPower
                /// </summary>
                public const string GhoulChargeRETURN_OF_THE_LICH_KING3 = "RLK_Prologue_Arthas_004p";

                /// <summary>
                /// <b>Deathrattle:</b> Summon every minion killed by this weapon.<br/>
                /// 7-Cost Weapon
                /// </summary>
                public const string FrostmourneRETURN_OF_THE_LICH_KING = "RLK_Prologue_Frostmourne_001";

                /// <summary>
                /// <b>Casts When Drawn</b> Equip Frostmourne.<br/>
                /// Spell
                /// </summary>
                public const string Frostmourne_TheLichKingsBlade = "RLK_Prologue_Frostmourne_001s";

                /// <summary>
                /// (No Text)<br/>
                /// 0-Cost Hero
                /// </summary>
                public const string TheLichKingHeroicRETURN_OF_THE_LICH_KING = "RLK_Prologue_LichKing_004hp2";

                /// <summary>
                /// (No Text)<br/>
                /// 0-Cost Hero
                /// </summary>
                public const string MalganisHeroic = "RLK_Prologue_MalGanis_001hb";

                /// <summary>
                /// <b>Hero Power</b> Summon a 1/1 Ghoul with <b>Charge</b>. It dies at end of turn.<br/>
                /// 2-Cost HeroPower
                /// </summary>
                public const string GhoulChargeRETURN_OF_THE_LICH_KING4 = "RLK_Prologue_MalGanis_001p";

                /// <summary>
                /// After your hero attacks and kills a minion, gain 2 <b>Corpses</b>.<br/>
                /// 3-Cost Weapon
                /// </summary>
                public const string Soulbreaker = "RLK_Prologue_RLK_012";

                /// <summary>
                /// The next spell you cast this turn costs (2) less.<br/>
                /// Enchantment
                /// </summary>
                public const string GlacialAdvanceEnchantment1 = "RLK_Prologue_RLK_025e";

                /// <summary>
                /// The next spell you cast this turn costs (2) less.<br/>
                /// Enchantment
                /// </summary>
                public const string GlacialAdvanceEnchantment2 = "RLK_Prologue_RLK_025o";

                /// <summary>
                /// Detonate a <b>Corpse</b> to deal $1 damage to all minions. If any are still alive, repeat this.<br/>
                /// 5-Cost Spell
                /// </summary>
                public const string CorpseExplosion = "RLK_Prologue_RLK_035";

                /// <summary>
                /// Give your hero +5 Health. Spend 3 <b>Corpses</b> to gain 5 more and draw a card.<br/>
                /// 2-Cost Spell
                /// </summary>
                public const string VampiricBlood = "RLK_Prologue_RLK_051";

                /// <summary>
                /// <b>Battlecry:</b> Shred a random minion in your deck to gain 3 <b>Corpses.</b><br/>
                /// 3-Cost 3/4 Mechanical Minion
                /// </summary>
                public const string MeatGrinder = "RLK_Prologue_RLK_120";

                /// <summary>
                /// <b>Taunt</b> <b>Battlecry:</b> Raise up to 6 <b>Corpses</b> as 1/2 Risen Footmen with <b>Taunt</b>.<br/>
                /// 8-Cost 8/8 Undead Minion
                /// </summary>
                public const string BoneguardCommanderRETURN_OF_THE_LICH_KING = "RLK_Prologue_RLK_506";

                /// <summary>
                /// +1 Attack.<br/>
                /// Enchantment
                /// </summary>
                public const string GraveStrength_GraveMarkEnchantmentRETURN_OF_THE_LICH_KING2 = "RLK_Prologue_RLK_707e";

                /// <summary>
                /// +3 Attack.<br/>
                /// Enchantment
                /// </summary>
                public const string GraveStrength_GraveForceEnchantment2 = "RLK_Prologue_RLK_707e2";

                /// <summary>
                /// <b>Battlecry:</b> Destroy all other minions. Gain 1 <b>Corpse</b> for each enemy destroyed.<br/>
                /// 8-Cost 5/5 Undead Minion
                /// </summary>
                public const string Soulstealer = "RLK_Prologue_RLK_741";

                /// <summary>
                /// +1/+2.<br/>
                /// Enchantment
                /// </summary>
                public const string BonediggerGeist_DugUpEnchantment2 = "RLK_Prologue_RLK_753e";

                /// <summary>
                /// Fill your board with random Undead.<br/>
                /// 9-Cost Spell
                /// </summary>
                public const string TheScourgeRETURN_OF_THE_LICH_KING = "RLK_Prologue_TheScourge_003s";

                /// <summary>
                /// (No Text)<br/>
                /// 
                /// </summary>
                public const string BloodDeckArt = "RLK_Shop_DKBlood";

                /// <summary>
                /// (No Text)<br/>
                /// 
                /// </summary>
                public const string FrostDeckArt = "RLK_Shop_DKFrost";

                /// <summary>
                /// (No Text)<br/>
                /// 
                /// </summary>
                public const string UnholyDeckArt = "RLK_Shop_DKUnholy";

                /// <summary>
                /// <b>Lifesteal</b><br/>
                /// 1-Cost 1/1 Undead Minion
                /// </summary>
                public const string ArcaniteRipper_BlightheadToken = "ETC_423t";

                /// <summary>
                /// Copied <b>Deathrattle</b> from {0}.<br/>
                /// Enchantment
                /// </summary>
                public const string DeathGrowl_WallOfDeathEnchantment = "ETC_424e";

                /// <summary>
                /// +2/+2.<br/>
                /// Enchantment
                /// </summary>
                public const string HarmonicMetal_HarmonicPresenceEnchantment = "ETC_427e";

                /// <summary>
                /// +4/+4.<br/>
                /// Enchantment
                /// </summary>
                public const string HarmonicMetal_DissonantPresenceEnchantment = "ETC_427e2";

                /// <summary>
                /// Give 2 random minions in your hand +4/+4. <i>(Swaps each turn.)</i><br/>
                /// 3-Cost Spell
                /// </summary>
                public const string HarmonicMetal_DissonantMetalToken = "ETC_427t";

                /// <summary>
                /// Copied <b>Deathrattle</b> from {0}.<br/>
                /// Enchantment
                /// </summary>
                public const string Boneshredder_ShreddingEnchantment = "ETC_428e";

                /// <summary>
                /// (No Text)<br/>
                /// 1-Cost 1/1 Undead Minion
                /// </summary>
                public const string ScreamingBanshee_DieHardFanToken = "ETC_522t";

                /// <summary>
                /// <b>Charge</b> <b>Taunt</b><br/>
                /// 9-Cost 9/9 Undead/Beast Minion
                /// </summary>
                public const string CageHead_BlightBoarToken = "ETC_526t";

                /// <summary>
                /// Your next card costs (1) more.<br/>
                /// Enchantment
                /// </summary>
                public const string DistressedKvaldir_FrostFeverEnchantment1 = "TTN_450e";

                /// <summary>
                /// Costs (1) more.<br/>
                /// Enchantment
                /// </summary>
                public const string DistressedKvaldir_FrostFeverEnchantment2 = "TTN_450e2";

                /// <summary>
                /// <b>Casts When Drawn</b> Take 2 damage. Restore 2 Health to the enemy hero.<br/>
                /// 1-Cost Spell
                /// </summary>
                public const string DistressedKvaldir_BloodPlagueToken = "TTN_450t";

                /// <summary>
                /// <b>Casts When Drawn</b> Take 2 damage. Summon a 2/2 Undead for your opponent.<br/>
                /// 1-Cost Spell
                /// </summary>
                public const string DistressedKvaldir_UnholyPlagueToken = "TTN_450t2";

                /// <summary>
                /// <b>Casts When Drawn</b> Take 2 damage. Your next card costs (1) more <i>(up to 10)</i>.<br/>
                /// 1-Cost Spell
                /// </summary>
                public const string DistressedKvaldir_FrostPlagueToken = "TTN_450t3";

                /// <summary>
                /// <b>Forged</b> <b>Battlecry:</b> Gain 3 <b>Corpses</b>. Deal 3 damage.<br/>
                /// 3-Cost 3/3 Undead Minion
                /// </summary>
                public const string Eulogizer_EulogizerToken = "TTN_457t";

                /// <summary>
                /// Your next spell costs (3) less and has <b>Spell Damage +3</b>.<br/>
                /// Enchantment
                /// </summary>
                public const string ThePrimus_ChillOfDeathEnchantment = "TTN_737e";

                /// <summary>
                /// Costs (3) less.<br/>
                /// Enchantment
                /// </summary>
                public const string ThePrimus_ChilledEnchantment = "TTN_737e1";

                /// <summary>
                /// Destroy an enemy minion. This minion and your hero gain its Health.<br/>
                /// 0-Cost Spell
                /// </summary>
                public const string ThePrimus_RunesOfBloodToken = "TTN_737t";

                /// <summary>
                /// Summon two 3/3 Undead with <b>Taunt</b> and <b>Reborn</b>.<br/>
                /// 0-Cost Spell
                /// </summary>
                public const string ThePrimus_RunesOfTheUnholyToken = "TTN_737t1";

                /// <summary>
                /// <b>Taunt</b> <b>Reborn</b><br/>
                /// 3-Cost 3/3 Undead Minion
                /// </summary>
                public const string ThePrimus_ServantOfThePrimusToken = "TTN_737t2";

                /// <summary>
                /// The next spell you cast costs (3) less and has <b>Spell Damage +3</b>.<br/>
                /// 0-Cost Spell
                /// </summary>
                public const string ThePrimus_RunesOfFrostToken = "TTN_737t3";

                /// <summary>
                /// Increased Health.<br/>
                /// Enchantment
                /// </summary>
                public const string ThePrimus_BloodOfThePrimusEnchantmentToken = "TTN_737te";

                /// <summary>
                /// Can't be played next turn.<br/>
                /// Enchantment
                /// </summary>
                public const string FrozenOver_FrozenSolidEnchantment = "TTN_744e1";

                /// <summary>
                /// Diseases are unending.<br/>
                /// Enchantment
                /// </summary>
                public const string Helya_HelyaEnchantment = "TTN_850e1";

                /// <summary>
                /// +2/+2<br/>
                /// Enchantment
                /// </summary>
                public const string SinisterSoulcage_WithSoulEnchantment = "YOG_513e";

                /// <summary>
                /// <b>Rush</b><br/>
                /// 4-Cost 4/5 Undead Minion
                /// </summary>
                public const string DarkTransformation_UndeadMonstrosityToken = "RLK_057t";

                /// <summary>
                /// (No Text)<br/>
                /// 5-Cost 5/5 Undead/Dragon Minion
                /// </summary>
                public const string FrostwyrmsFury_FrostwyrmTokenPATH_OF_ARTHAS1 = "RLK_063t";

                /// <summary>
                /// +1 Attack.<br/>
                /// Enchantment
                /// </summary>
                public const string YmirjarFrostbreaker_ShatteringStrengthEnchantment1 = "RLK_110e";

                /// <summary>
                /// <b>Taunt</b><br/>
                /// 2-Cost 2/2 Undead Minion
                /// </summary>
                public const string TombGuardians_MenacingZombieToken1 = "RLK_118t3";

                /// <summary>
                /// <b>Taunt</b> <i>Doesn't leave a <b>Corpse</b>.</i><br/>
                /// 1-Cost 1/1 Undead Minion
                /// </summary>
                public const string BoneguardCommander_RisenGroomToken = "RLK_506t";

                /// <summary>
                /// Costs (1) less.<br/>
                /// Enchantment
                /// </summary>
                public const string RimefangSword_FreezyBreezyEnchantment = "RLK_710e";

                /// <summary>
                /// Increased Attack.<br/>
                /// Enchantment
                /// </summary>
                public const string ViciousBloodworm_BloodGiftEnchantment1 = "RLK_711e";

                /// <summary>
                /// +1/+1.<br/>
                /// Enchantment
                /// </summary>
                public const string BloodTap_TappedBloodEnchantment1 = "RLK_712e";

                /// <summary>
                /// At the end of your opponent's turns, take 2 damage.<br/>
                /// Enchantment
                /// </summary>
                public const string BloodBoil_BoilingBloodEnchantment1 = "RLK_730e";

                /// <summary>
                /// +2 Attack.<br/>
                /// Enchantment
                /// </summary>
                public const string DarkfallenNeophyte_FallenToDarkEnchantment1 = "RLK_731e";

                /// <summary>
                /// Deal $3 damage to an enemy and <b>Freeze</b> it. Deal $1 damage to all other enemies.<br/>
                /// 3-Cost Spell
                /// </summary>
                public const string HowlingBlast = "RLK_Prologue_RLK_015";

                /// <summary>
                /// Deal $3 damage to a minion. If that kills it, summon a 2/2 Zombie with <b>Rush</b>.<br/>
                /// 2-Cost Spell
                /// </summary>
                public const string PlagueStrike = "RLK_Prologue_RLK_018";

                /// <summary>
                /// Deal $2 damage to an enemy and <b>Freeze</b> it.<br/>
                /// 1-Cost Spell
                /// </summary>
                public const string IcyTouchPATH_OF_ARTHAS = "RLK_Prologue_RLK_038";

                /// <summary>
                /// Refresh 2 Mana Crystals.<br/>
                /// 0-Cost Spell
                /// </summary>
                public const string HornOfWinter = "RLK_Prologue_RLK_042";

                /// <summary>
                /// <b>Taunt</b> <b>Battlecry:</b> Summon two copies of this minion.<br/>
                /// 4-Cost 1/3 Undead Minion
                /// </summary>
                public const string NerubianSwarmguard = "RLK_Prologue_RLK_062";

                /// <summary>
                /// Deal $5 damage. <b>Freeze</b> all enemy minions. Summon a 5/5 Frostwyrm.<br/>
                /// 7-Cost Spell
                /// </summary>
                public const string FrostwyrmsFuryPATH_OF_ARTHAS = "RLK_Prologue_RLK_063";

                /// <summary>
                /// (No Text)<br/>
                /// 5-Cost 5/5 Undead/Dragon Minion
                /// </summary>
                public const string FrostwyrmsFury_FrostwyrmTokenPATH_OF_ARTHAS2 = "RLK_Prologue_RLK_063t";

                /// <summary>
                /// After you cast a spell, deal 1 damage to two random enemies.<br/>
                /// 2-Cost 2/3 Elemental Minion
                /// </summary>
                public const string Deathchiller = "RLK_Prologue_RLK_083";

                /// <summary>
                /// Destroy the highest Attack enemy minion.<br/>
                /// 3-Cost Spell
                /// </summary>
                public const string Asphyxiate = "RLK_Prologue_RLK_087";

                /// <summary>
                /// <b>Battlecry:</b> Gain +1 Attack for each Frost spell in your hand.<br/>
                /// 1-Cost 1/2 Minion
                /// </summary>
                public const string YmirjarFrostbreaker = "RLK_Prologue_RLK_110";

                /// <summary>
                /// +1 Attack.<br/>
                /// Enchantment
                /// </summary>
                public const string YmirjarFrostbreaker_ShatteringStrengthEnchantment2 = "RLK_Prologue_RLK_110e";

                /// <summary>
                /// Summon two 2/2 Zombies with <b>Taunt</b>. Spend 4 <b>Corpses</b> to give them <b>Reborn</b>.<br/>
                /// 4-Cost Spell
                /// </summary>
                public const string TombGuardians = "RLK_Prologue_RLK_118";

                /// <summary>
                /// <b>Taunt</b><br/>
                /// 2-Cost 2/2 Undead Minion
                /// </summary>
                public const string TombGuardians_MenacingZombieToken2 = "RLK_Prologue_RLK_118t3";

                /// <summary>
                /// <b>Battlecry:</b> Spend up to 5 <b>Corpses</b>. Deal 2 damage to a random enemy for each.<br/>
                /// 6-Cost 5/5 Undead Minion
                /// </summary>
                public const string MarrowManipulator = "RLK_Prologue_RLK_505";

                /// <summary>
                /// Deal $4 damage. Your next spell this turn costs (2) less.<br/>
                /// 3-Cost Spell
                /// </summary>
                public const string GlacialAdvance = "RLK_Prologue_RLK_512";

                /// <summary>
                /// <b>Battlecry:</b> Give a minion in your hand Attack equal to this minion's Attack.<br/>
                /// 2-Cost 3/2 Beast Minion
                /// </summary>
                public const string ViciousBloodworm = "RLK_Prologue_RLK_711";

                /// <summary>
                /// Increased Attack.<br/>
                /// Enchantment
                /// </summary>
                public const string ViciousBloodworm_BloodGiftEnchantment2 = "RLK_Prologue_RLK_711e";

                /// <summary>
                /// Give all minions in your hand +1/+1. Spend 3 <b>Corpses</b> to give them +1/+1 more.<br/>
                /// 2-Cost Spell
                /// </summary>
                public const string BloodTapPATH_OF_ARTHAS = "RLK_Prologue_RLK_712";

                /// <summary>
                /// +1/+1.<br/>
                /// Enchantment
                /// </summary>
                public const string BloodTap_TappedBloodEnchantment2 = "RLK_Prologue_RLK_712e";

                /// <summary>
                /// <b>Lifesteal</b> Infect all enemy minions. At the end of your turns, they take 2 damage.<br/>
                /// 5-Cost Spell
                /// </summary>
                public const string BloodBoil = "RLK_Prologue_RLK_730";

                /// <summary>
                /// At the end of your opponent's turns, take 2 damage.<br/>
                /// Enchantment
                /// </summary>
                public const string BloodBoil_BoilingBloodEnchantment2 = "RLK_Prologue_RLK_730e";

                /// <summary>
                /// <b>Battlecry:</b> Spend 2 <b>Corpses</b> to give all minions in your hand +2 Attack.<br/>
                /// 3-Cost 2/5 Undead Minion
                /// </summary>
                public const string DarkfallenNeophyte = "RLK_Prologue_RLK_731";

                /// <summary>
                /// +2 Attack.<br/>
                /// Enchantment
                /// </summary>
                public const string DarkfallenNeophyte_FallenToDarkEnchantment2 = "RLK_Prologue_RLK_731e";

                /// <summary>
                /// <b>Battlecry:</b> Spend up to 3 <b>Corpses</b>. <b>Freeze</b> that many enemy minions.<br/>
                /// 4-Cost Weapon
                /// </summary>
                public const string MightOfMenethil = "RLK_Prologue_RLK_740";

                /// <summary>
                /// <b>Battlecry:</b> Resurrect your highest Cost minion. Give it +2/+2, <b>Reborn</b>, and <b>Lifesteal</b>.<br/>
                /// 4-Cost 5/5 Elemental/Beast Minion
                /// </summary>
                public const string KoboldMiner_TheAzeriteRatToken = "WW_001t26";

                /// <summary>
                /// +2/+2, <b>Reborn</b>, and <b>Lifesteal</b>.<br/>
                /// Enchantment
                /// </summary>
                public const string KoboldMiner_AzeriteSoulToken = "WW_001t26e";

                /// <summary>
                /// After you excavate, resummon one Pile of Bones.<br/>
                /// Enchantment
                /// </summary>
                public const string PileofBones_PileOfBonesEnchantment = "WW_324e";

                /// <summary>
                /// Your next card this turn costs (7).<br/>
                /// Enchantment
                /// </summary>
                public const string HarrowingOx_OxChillEnchantment = "WW_356e";

                /// <summary>
                /// Increased Health.<br/>
                /// Enchantment
                /// </summary>
                public const string MawandPaw_FamilyValuesEnchantment = "WW_357e";

                /// <summary>
                /// <b>Rush</b> At the end of your turn, this minion dies.<br/>
                /// 1-Cost 1/1 Undead Minion
                /// </summary>
                public const string CropRotation_GnomeOnTheRangeToken = "WW_368t";

                /// <summary>
                /// Costs less<br/>
                /// Enchantment
                /// </summary>
                public const string ToysnatchingGeist_CollectionBonusEnchantment = "MIS_006e1";

                /// <summary>
                /// <b>Gigantic</b> <b>Battlecry:</b> <b>Discover</b> an Undead. Reduce its Cost by this minion's Attack.<br/>
                /// 8-Cost 8/8 Undead Minion
                /// </summary>
                public const string ToysnatchingGeist_ToysnatchingGeistToken = "MIS_006t";

                /// <summary>
                /// -5/-5.<br/>
                /// Enchantment
                /// </summary>
                public const string HelmofHumiliation_HumiliatedEnchantment = "MIS_100e";

                /// <summary>
                /// This deck has cards from all classes and spell schools.<br/>
                /// Spell
                /// </summary>
                public const string SplendiferousWhizbang_RainbowDeckToken = "TOY_700t2";

                /// <summary>
                /// Cast {0} when the minion dies.<br/>
                /// Enchantment
                /// </summary>
                public const string SilkStitching_DarknessWithinEnchantment = "TOY_822e";

                /// <summary>
                /// +1/+1.<br/>
                /// Enchantment
                /// </summary>
                public const string LesserSpinelSpellstone_LesserSoulbindEnchantment = "TOY_825e";

                /// <summary>
                /// +2/+2.<br/>
                /// Enchantment
                /// </summary>
                public const string LesserSpinelSpellstone_SoulbindEnchantment = "TOY_825e2";

                /// <summary>
                /// +3/+3.<br/>
                /// Enchantment
                /// </summary>
                public const string LesserSpinelSpellstone_GreaterSoulbindEnchantment = "TOY_825e3";

                /// <summary>
                /// Give Undead in your hand +2/+2. <i>(Gain 5 <b>Corpses</b> to upgrade.)</i><br/>
                /// 1-Cost Spell
                /// </summary>
                public const string LesserSpinelSpellstone_SpinelSpellstoneToken = "TOY_825t";

                /// <summary>
                /// Give Undead in your hand +3/+3.<br/>
                /// 1-Cost Spell
                /// </summary>
                public const string LesserSpinelSpellstone_GreaterSpinelSpellstoneToken = "TOY_825t2";

                /// <summary>
                /// <b>Deathrattle:</b> Deal 1 damage to all minions.<br/>
                /// Enchantment
                /// </summary>
                public const string ThreadsofDespair_ThreadsOfTheDeadEnchantment = "TOY_826e";

                /// <summary>
                /// +2/+2.<br/>
                /// Enchantment
                /// </summary>
                public const string AmateurPuppeteer_StringsAttachedEnchantment = "TOY_828e4";

                /// <summary>
                /// <b>Mini</b>, <b>Taunt</b> <b>Deathrattle:</b> Give Undead in your hand +2/+2.<br/>
                /// 1-Cost 1/1 Undead Minion
                /// </summary>
                public const string AmateurPuppeteer_AmateurPuppeteerToken = "TOY_828t";

                /// <summary>
                /// Deal $3 damage, with crushing <i>brawn!</i> <b>Discover</b> an Undead, to serve as your <i>pawn!</i><br/>
                /// 2-Cost HeroPower
                /// </summary>
                public const string PulsingPumpkinsHeroic1 = "TOY_829hp";

                /// <summary>
                /// Deal $3 damage, with crushing <i>brawn!</i> My army shall be yours, if my Head is <i>drawn!</i><br/>
                /// 2-Cost HeroPower
                /// </summary>
                public const string PulsingPumpkinsHeroic2 = "TOY_829hp3";

                /// <summary>
                /// <b>When Drawn, this Casts</b> and your enemy will <i>cower!</i> Imbue the souls of Undead into your <i>Hero Power!</i><br/>
                /// 2-Cost Spell
                /// </summary>
                public const string TheHeadlessHorseman_HorsemansHeadToken = "TOY_829t";

                /// <summary>
                /// <b>Battlecry:</b> Destroy the enemy minion with the most <i>Attack!</i> Shuffle my Head into your deck, you must get it <i>back!</i><br/>
                /// 6-Cost Hero
                /// </summary>
                public const string TheHeadlessHorseman_TheHeadlessHorsemanToken = "TOY_829t2";

                /// <summary>
                /// <b>Deathrattle:</b> Summon the minion stitched to this.<b>Deathrattle:</b> Summon {0}.<br/>
                /// Enchantment
                /// </summary>
                public const string DrStitchensew_StitchedToysEnchantment = "TOY_830e";

                /// <summary>
                /// <b>Hero Power</b> Summon a 1/1 Ghoul with <b>Charge</b>. It dies at end of turn.<br/>
                /// 2-Cost HeroPower
                /// </summary>
                public const string GhoulChargeTUTORIAL = "TUTR_HERO_11bp";

                /// <summary>
                /// <b>Charge</b> At the end of your turn, this minion dies.<br/>
                /// 1-Cost 1/1 Undead Minion
                /// </summary>
                public const string FrailGhoul = "TUTR_HERO_11bpt";

                /// <summary>
                /// (No Text)<br/>
                /// 1-Cost 2/1 Undead Minion
                /// </summary>
                public const string RisenGhoulToken = "TUTR_RLK_008t";

                /// <summary>
                /// Summon five 2/1 Risen Ghouls.<br/>
                /// 4-Cost Spell
                /// </summary>
                public const string ArmyOfTheDeadTUTORIAL = "TUTR_RLK_060";

                /// <summary>
                /// <b>Battlecry</b>: Summon two 2/1 Risen Ghouls.<br/>
                /// 3-Cost 2/2 Minion
                /// </summary>
                public const string BattlefieldNecromancer = "TUTR_RLK_061";

                /// <summary>
                /// Deal $5 damage. <b>Freeze</b> all enemy minions. Summon a 5/5 Frostwyrm.<br/>
                /// 6-Cost Spell
                /// </summary>
                public const string FrostwyrmsFuryTUTORIAL = "TUTR_RLK_063";

                /// <summary>
                /// (No Text)<br/>
                /// 5-Cost 5/5 Undead/Dragon Minion
                /// </summary>
                public const string FrostwyrmsFury_FrostwyrmTokenTUTORIAL = "TUTR_RLK_063t";

                /// <summary>
                /// (No Text)<br/>
                /// 5-Cost Weapon
                /// </summary>
                public const string FrostmourneTUTORIAL = "TUTR_RLK_086";

                /// <summary>
                /// (No Text)<br/>
                /// 1-Cost 1/3 Undead Minion
                /// </summary>
                public const string BodyBagger = "TUTR_RLK_503";

                /// <summary>
                /// <b>Taunt</b> <b>Battlecry:</b> Summon four 2/1 Risen Ghouls.<br/>
                /// 6-Cost 5/4 Undead Minion
                /// </summary>
                public const string BoneguardCommanderTUTORIAL = "TUTR_RLK_506";

                /// <summary>
                /// Give all friendly minions +2/+1. <i>(+2 Attack/+1 Health)</i><br/>
                /// 3-Cost Spell
                /// </summary>
                public const string GraveStrength = "TUTR_RLK_707";

                /// <summary>
                /// +2/+1.<br/>
                /// Enchantment
                /// </summary>
                public const string GraveStrength_GraveMarkEnchantmentTUTORIAL = "TUTR_RLK_707e1";

                /// <summary>
                /// (No Text)<br/>
                /// 4-Cost 8/4 Undead Minion
                /// </summary>
                public const string StitchedGiant = "TUTR_RLK_744";

                /// <summary>
                /// (No Text)<br/>
                /// 1-Cost 2/2 Undead Minion
                /// </summary>
                public const string BonediggerGeist = "TUTR_RLK_753";

                /// <summary>
                /// Fill your board with random Undead.<br/>
                /// 9-Cost Spell
                /// </summary>
                public const string TheScourgeTUTORIAL = "TUTR_TheScourge_003s";

                /// <summary>
                /// (No Text)<br/>
                /// 0-Cost Hero
                /// </summary>
                public const string LichKing = "TUTR_Uther";

                /// <summary>
                /// (No Text)<br/>
                /// 1-Cost 1/1 Undead Minion
                /// </summary>
                public const string GhoulsNight_SlumberingGhoulToken = "VAC_445t";

                /// <summary>
                /// <b>Reborn</b><br/>
                /// 1-Cost 1/1 Undead/Beast Minion
                /// </summary>
                public const string DreadhoundHandler_DreadhoundToken = "VAC_514t";

                /// <summary>
                /// <b>Starship</b> <i>(Costs (5) Mana to launch.)</i><b>Starship</b> <i>(Made of {0} pieces.)</i><br/>
                /// 0/0 Minion
                /// </summary>
                public const string ArkoniteDefenseCrystal_TheSpiritsPassageToken = "GDB_100t4";

                /// <summary>
                /// <b>Spellburst:</b> Trigger a random friendly minion's <b>Deathrattle</b>.<br/>
                /// Enchantment
                /// </summary>
                public const string GuidingFigure_GuidingFigureEnchantment = "GDB_106e";

                /// <summary>
                /// <b>Deathrattle:</b> Summon a minion with Cost equal to this minion's Attack <i>(up to 10)</i>.<br/>
                /// Enchantment
                /// </summary>
                public const string SoulboundSpire_SoulboundSpireEnchantment = "GDB_112e";

                /// <summary>
                /// +5 Health.<br/>
                /// Enchantment
                /// </summary>
                public const string AirlockBreach_BreachedAirEnchantment = "GDB_113e";

                /// <summary>
                /// <b>Taunt</b><br/>
                /// 5-Cost 5/5 Undead/Draenei Minion
                /// </summary>
                public const string AirlockBreach_UnfortunateSoulToken = "GDB_113t";

                /// <summary>
                /// Your next card this turn costs <b>Corpses</b> instead of Mana.<br/>
                /// Enchantment
                /// </summary>
                public const string ExarchMaladaar_NecromanticPowerEnchantment = "GDB_470e";

                /// <summary>
                /// Costs <b>Corpses</b> instead of mana.<br/>
                /// Enchantment
                /// </summary>
                public const string ExarchMaladaar_CostsCorpsesEnchantment = "GDB_470e2";

                /// <summary>
                /// For the rest of the game, your Zerg have +1 Attack.<br/>
                /// Enchantment
                /// </summary>
                public const string Infestor_ForTheSwarmEnchantment1 = "SC_002e";

                /// <summary>
                /// +1 Attack.<br/>
                /// Enchantment
                /// </summary>
                public const string Infestor_ForTheSwarmEnchantment2 = "SC_002e2";

                /// <summary>
                /// <b>Deathrattle:</b> Deal damage equal to this minion's Attack to all enemy minions.<br/>
                /// 1-Cost 1/1 Minion
                /// </summary>
                public const string UltraliskCavern_BanelingToken = "SC_019t";

                /// <summary>
                /// Reduced Health.<br/>
                /// Enchantment
                /// </summary>
                public const string HideousHusk_BloodSuckerEnchantment = "EDR_810e";

                /// <summary>
                /// Increased Health.<br/>
                /// Enchantment
                /// </summary>
                public const string HideousHusk_BloodSoakedEnchantment = "EDR_810e2";

                /// <summary>
                /// At the end of your turn, your hero steals 1 Health from the lowest Health enemy.<br/>
                /// 1-Cost 0/2 Beast Minion
                /// </summary>
                public const string HideousHusk_BloatedLeechToken = "EDR_810t";

                /// <summary>
                /// Summon two 1/1 Ants.<br/>
                /// 1-Cost Spell
                /// </summary>
                public const string MorbidSwarm_ContaminatedColony = "EDR_813a";

                /// <summary>
                /// (No Text)<br/>
                /// 1-Cost 1/1 Beast/Undead Minion
                /// </summary>
                public const string MorbidSwarm_AntHusk = "EDR_813at";

                /// <summary>
                /// Spend 2 <b>Corpses</b> to deal $4 damage to a minion.<br/>
                /// 1-Cost Spell
                /// </summary>
                public const string MorbidSwarm_BugBites = "EDR_813b";

                /// <summary>
                /// +1 Attack.<br/>
                /// Enchantment
                /// </summary>
                public const string MonstrousMosquito_SharedBloodEnchantment = "EDR_816e";

                /// <summary>
                /// At the start of your turn, combine with any other friendly Beetles and reform Nythendra.<br/>
                /// 1-Cost 1/1 Undead/Beast Minion
                /// </summary>
                public const string Nythendra_NythendricBeetleToken = "EDR_818t";

                /// <summary>
                /// {0}<br/>
                /// Enchantment
                /// </summary>
                public const string Ursoc_DefeatedSpiritEnchantment = "EDR_819e";

                /// <summary>
                /// Increased Health.<br/>
                /// Enchantment
                /// </summary>
                public const string _32StandardHealthIncrease = "EDR_XXX";

                /// <summary>
                /// <b>Taunt</b><br/>
                /// 4-Cost 4/4 Dragon Minion
                /// </summary>
                public const string FrostburnMatriarch_FrostburnBroodlingToken = "FIR_901t";

                /// <summary>
                /// Increased Stats.<br/>
                /// Enchantment
                /// </summary>
                public const string Volcoross_VoraciousAppetiteEnchantment = "FIR_951e";

                /// <summary>
                /// Spend 10 <b>Corpses</b> to gain +10/+10.<br/>
                /// Spell
                /// </summary>
                public const string Volcoross_TailSmashToken = "FIR_951t2";

                /// <summary>
                /// Spend 20 <b>Corpses</b> to gain +20/+20.<br/>
                /// Spell
                /// </summary>
                public const string Volcoross_FieryChompToken = "FIR_951t3";

                /// <summary>
                /// Spend 30 <b>Corpses</b> to gain +30/+30.<br/>
                /// Spell
                /// </summary>
                public const string Volcoross_LavaWaveToken = "FIR_951t4";

                /// <summary>
                /// <b>Deathrattle:</b> Open Terror's Grave. It has "<b>Deathrattle:</b> Resummon Tyrax."<br/>
                /// 5-Cost 8/8 Undead/Beast Minion
                /// </summary>
                public const string ReanimatetheTerror_TyraxBoneTerrorToken = "TLC_433t";

                /// <summary>
                /// Deal 4 damage. <b>Deathrattle:</b> Resummon Tyrax, Bone Terror.<br/>
                /// 5-Cost Location
                /// </summary>
                public const string ReanimatetheTerror_TerrorsGraveToken = "TLC_433t2";

                /// <summary>
                /// If you play the <b>Discover</b>ed card this turn, also choose one of the other two options.<br/>
                /// Enchantment
                /// </summary>
                public const string CryptMap_CryptMapPlayerEnchantEnchantment = "TLC_435e";

                /// <summary>
                /// Costs (2) more.<br/>
                /// Enchantment
                /// </summary>
                public const string WaveofTar_StuckEnchantment = "TLC_439e2";

                /// <summary>
                /// <b>Taunt</b><br/>
                /// 2-Cost 2/2 Undead/Beast Minion
                /// </summary>
                public const string ReluctantWrangler_ReanimatedOssodonToken = "TLC_443t";
            }
        }
    }
}