namespace HearthDb
{
    /* THIS CLASS WAS GENERATED BY HearthDb.CardIdGenerator. DO NOT EDIT. */
    public partial class CardIds
    {
        public partial class NonCollectible
        {
            public class DreamCards
            {
                public const string LaughingSister = "DREAM_01";
                public const string YseraAwakens = "DREAM_02";
                public const string EmeraldDrake = "DREAM_03";
                public const string Dream = "DREAM_04";
                public const string NightmareExpert1 = "DREAM_05";
                public const string RepurposedEnchantmentTavernBrawl = "TB_MP_02e";
                public const string LaughingSisterVanilla = "VAN_DREAM_01";
                public const string YseraAwakensVanilla = "VAN_DREAM_02";
                public const string EmeraldDrakeVanilla = "VAN_DREAM_03";
                public const string DreamVanilla = "VAN_DREAM_04";
                public const string NightmareVanilla = "VAN_DREAM_05";
            }
        }
    }
}