namespace HearthDb.Enums
{
	public enum BnetGameType
	{
		BGT_UNKNOWN = 0,
		BGT_FRIENDS = 1,
		BGT_RANKED_STANDARD = 2,
		BGT_ARENA = 3,
		BGT_VS_AI = 4,
		BGT_TUTORIAL = 5,
		BGT_ASYNC = 6,
		BGT_NEWBIE = 9,
		BGT_CASUAL_STANDARD = 7,
		BGT_TEST1 = 8,
		BGT_TEST2 = 9,
		BGT_TEST3 = 10,
		BGT_TAVERNBRAWL_PVP = 16,
		BGT_TAVERNBRAWL_1P_VERSUS_AI = 17,
		BGT_TAVERNBRAWL_2P_COOP = 18,
		BGT_RANKED_WILD = 30,
		BGT_CASUAL_WILD = 31,
		BGT_LAST = 32
	}
}