namespace HearthDb.Enums
{
    using System.Collections.Generic;
    /* THIS FILE WAS GENERATED BY HearthDb.EnumsGenerator. DO NOT EDIT. */

    public static class RaceUtils
    {
        public static Dictionary<int, Race> TagRaceMap = new Dictionary<int, Race>() {
        { 2524, Race.BLOODELF },
        { 2525, Race.DRAENEI },
        { 2526, Race.DWARF },
        { 2527, Race.GNOME },
        { 2528, Race.GOBLIN },
        { 2529, Race.HUMAN },
        { 2530, Race.NIGHTELF },
        { 2531, Race.ORC },
        { 2532, Race.TAUREN },
        { 2533, Race.TROLL },
        { 2534, Race.UNDEAD },
        { 2535, Race.WORGEN },
        { 2536, Race.MURLOC },
        { 2537, Race.DEMON },
        { 2538, Race.SCOURGE },
        { 2539, Race.MECHANICAL },
        { 2540, Race.ELEMENTAL },
        { 2541, Race.OGRE },
        { 2542, Race.BEAST },
        { 2543, Race.TOTEM },
        { 2544, Race.NERUBIAN },
        { 2522, Race.PIRATE },
        { 2523, Race.DRAGON },
        { 2545, Race.EGG },
        { 2546, Race.QUILBOAR },
        { 2547, Race.CENTAUR },
        { 2548, Race.FURBOLG },
        { 2549, Race.HIGHELF },
        { 2550, Race.TREANT },
        { 2551, Race.OWLKIN },
        { 2552, Race.HALFORC },
        { 2553, Race.NAGA },
        { 2554, Race.OLDGOD },
        { 2555, Race.PANDAREN },
        { 2556, Race.GRONN },
        { 2584, Race.CELESTIAL },
        { 2585, Race.GNOLL },
        { 2586, Race.GOLEM },
        { 2587, Race.HARPY },
        { 2588, Race.VULPERA }
    };
    }
}