#region

using System.IO;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Formatting;
using Microsoft.CodeAnalysis.MSBuild;

#endregion

namespace HearthDb.CardIdGenerator
{
    internal class Program
    {
        private const string File = "../../../HearthDb/CardIds.cs";

        static void Main()
        {
            var @namespace = SyntaxFactory.NamespaceDeclaration(SyntaxFactory.IdentifierName("HearthDb"));
            var header = SyntaxFactory.ParseLeadingTrivia(@"/* THIS CLASS WAS GENERATED BY HearthDb.CardIdGenerator. DO NOT EDIT. */");
            var cCardIds =
                SyntaxFactory.ClassDeclaration("CardIds")
                             .AddModifiers(SyntaxFactory.Token(SyntaxKind.PublicKeyword))
                             .WithLeadingTrivia(header);
            var cCollectible = SyntaxFactory.ClassDeclaration("Collectible")
                                            .AddModifiers(SyntaxFactory.Token(SyntaxKind.PublicKeyword));
            cCollectible = SyntaxBuilder.GetCollectible(cCollectible);
            var cNonCollectible =
                SyntaxFactory.ClassDeclaration("NonCollectible").AddModifiers(SyntaxFactory.Token(SyntaxKind.PublicKeyword));
            cNonCollectible = SyntaxBuilder.GetNonCollectible(cNonCollectible);

            cCardIds = cCardIds.AddMembers(cCollectible);
            cCardIds = cCardIds.AddMembers(cNonCollectible);
            @namespace = @namespace.AddMembers(cCardIds);
            var root = Formatter.Format(@namespace, MSBuildWorkspace.Create());
            using(var sr = new StreamWriter(File))
                sr.Write(root.ToString());
        }
    }
}